package com.qimeng.media.ui.album

internal data class CharEntry(
    val canonical: String,
    val aliases: List<String>
)

internal data class SourceGroup(
    val canonical: String,
    val variants: List<String>,
    val characters: List<CharEntry> = emptyList()
)

// BUILTIN_GROUPS 更新规范（详见 docs/GUIDE_UI.md「角色检索表更新规范」）：
// 1. 新增前必须搜索确认无重复 canonical 或变体重叠
// 2. canonical 用最通用中文名，不带版本号（铁拳/最终幻想/生化危机）
// 3. 版本号合并到 variants：listOf("铁拳8","铁拳7","铁拳","Tekken 8","Tekken 7","Tekken")
// 4. 新 SourceGroup 追加到末尾，不插入中间
// 5. CharEntry canonical 用最常用中文名，aliases 含自身+中文别名+英文名+昵称，按长度降序
// 6. 出处+角色名是唯一标识，不同出处同名角色各自独立 CharEntry
// 7. 同一 SourceGroup 内禁止重复 CharEntry，发现重复必须合并 aliases
internal val BUILTIN_GROUPS = listOf(
    SourceGroup("尼尔 机械纪元", listOf("尼尔 机械纪元", "尼尔机械纪元", "NieR Automata", "NieR"), listOf(
        CharEntry("2B", listOf("2B", "2b", "二号机", "YoRHa No2 Type B")),
        CharEntry("A2", listOf("A2", "a2", "A型二号")),
        CharEntry("帕斯卡", listOf("帕斯卡", "Pascal")),
        CharEntry("司令官", listOf("司令官", "Commander", "怀特", "Yorha指挥官", "指挥官")),
        CharEntry("迪瓦拉", listOf("迪瓦拉", "迪瓦菈", "Devola")),
        CharEntry("波波拉", listOf("波波拉", "波波菈", "Popola")),
        CharEntry("凯妮", listOf("凯妮", "Kaine")),
        CharEntry("艾米尔", listOf("艾米尔", "Emil"))
    )),
    SourceGroup("守望先锋", listOf("守望先锋", "守望先锋 归来", "守望先锋2", "Overwatch", "OW"), listOf(
        CharEntry("天使", listOf("天使", "Mercy", "安吉拉", "齐格勒", "Angela")),
        CharEntry("猎空", listOf("猎空", "裂空", "Tracer", "莉娜")),
        CharEntry("DVA", listOf("DVA", "D.Va", "Dva", "宋哈娜", "Hana")),
        CharEntry("黑百合", listOf("黑百合", "Widowmaker", "艾米丽", "Amelie")),
        CharEntry("小美", listOf("小美", "Mei", "周美灵")),
        CharEntry("雾子", listOf("雾子", "Kiriko", "狐狸")),
        CharEntry("朱诺", listOf("朱诺", "Juno")),
        CharEntry("艾什", listOf("艾什", "Ashe", "莱德")),
        CharEntry("芙蕾雅", listOf("芙蕾雅", "Freya")),
        CharEntry("法老之鹰", listOf("法老之鹰", "法鸡", "Pharah", "法拉")),
        CharEntry("秩序之光", listOf("秩序之光", "Symmetra", "塞特娅")),
        CharEntry("查莉娅", listOf("查莉娅", "Zarya", "毛妹")),
        CharEntry("黑影", listOf("黑影", "Sombra")),
        CharEntry("安娜", listOf("安娜", "Ana")),
        CharEntry("布丽吉塔", listOf("布丽吉塔", "Brigitte", "锤妹")),
        CharEntry("莫伊拉", listOf("莫伊拉", "Moira")),
        CharEntry("回声", listOf("回声", "Echo")),
        CharEntry("狂鼠女王", listOf("狂鼠女王", "Junker Queen", "渣客女王")),
        CharEntry("伊拉莉", listOf("伊拉莉", "Illari")),
        CharEntry("探奇", listOf("探奇", "Venture")),
        CharEntry("温斯顿", listOf("温斯顿", "Winston")),
        CharEntry("安燃", listOf("安燃", "安然", "Anran"))
    )),
    SourceGroup("英雄联盟", listOf("英雄联盟", "League of Legends", "LOL", "撸啊撸"), listOf(
        CharEntry("阿狸", listOf("阿狸", "Ahri", "九尾妖狐", "狐狸")),
        CharEntry("金克丝", listOf("金克丝", "Jinx", "暴走萝莉")),
        CharEntry("拉克丝", listOf("拉克丝", "Lux", "光辉女郎")),
        CharEntry("伊芙琳", listOf("伊芙琳", "Evelynn", "寡妇制造者", "寡妇")),
        CharEntry("莫甘娜", listOf("莫甘娜", "Morgana")),
        CharEntry("戴安娜", listOf("戴安娜", "Diana", "皎月女神")),
        CharEntry("格温", listOf("格温", "Gwen")),
        CharEntry("好运姐", listOf("好运姐", "赏金", "赏金猎人", "Miss Fortune", "MF", "厄运小姐")),
        CharEntry("卡特琳娜", listOf("卡特琳娜", "卡特", "Katarina", "不祥之刃")),
        CharEntry("阿卡丽", listOf("阿卡丽", "Akali")),
        CharEntry("卡莎", listOf("卡莎", "Kaisa", "卡莎")),
        CharEntry("琴女", listOf("琴女", "Sona", "娑娜")),
        CharEntry("女枪", listOf("女枪", "Miss Fortune", "MF")),
        CharEntry("薇恩", listOf("薇恩", "Vayne", "暗夜猎手")),
        CharEntry("艾希", listOf("艾希", "Ashe", "寒冰射手")),
        CharEntry("凯特琳", listOf("凯特琳", "Caitlyn", "女警")),
        CharEntry("蔚", listOf("蔚", "Vi", "皮城执法官")),
        CharEntry("辛德拉", listOf("辛德拉", "Syndra")),
        CharEntry("蕾欧娜", listOf("蕾欧娜", "Leona", "日女")),
        CharEntry("婕拉", listOf("婕拉", "Zyra")),
        CharEntry("希瓦娜", listOf("希瓦娜", "Shyvana", "龙女")),
        CharEntry("厄运小姐", listOf("厄运小姐", "Miss Fortune", "好运姐", "赏金")),
        CharEntry("锐雯", listOf("锐雯", "Riven", "放逐之刃")),
        CharEntry("菲奥娜", listOf("菲奥娜", "Fiora", "剑姬")),
        CharEntry("艾瑞莉娅", listOf("艾瑞莉娅", "Irelia", "刀妹")),
        CharEntry("卡西奥佩娅", listOf("卡西奥佩娅", "Cassiopeia", "蛇女")),
        CharEntry("丽桑卓", listOf("丽桑卓", "Lissandra", "冰女")),
        CharEntry("卡蜜尔", listOf("卡蜜尔", "Camille", "青钢影")),
        CharEntry("霞", listOf("霞", "Xayah")),
        CharEntry("佐伊", listOf("佐伊", "Zoe")),
        CharEntry("妮蔻", listOf("妮蔻", "Neeko")),
        CharEntry("塞娜", listOf("塞娜", "Senna")),
        CharEntry("萨勒芬妮", listOf("萨勒芬妮", "Seraphine")),
        CharEntry("泽丽", listOf("泽丽", "Zeri")),
        CharEntry("薇古丝", listOf("薇古丝", "Vex")),
        CharEntry("奎因", listOf("奎因", "Quinn", "德玛西亚之翼")),
        CharEntry("希维尔", listOf("希维尔", "Sivir", "轮子妈")),
        CharEntry("崔丝塔娜", listOf("崔丝塔娜", "Tristana", "小炮")),
        CharEntry("波比", listOf("波比", "Poppy", "圣锤之毅")),
        CharEntry("莉莉娅", listOf("莉莉娅", "Lillia")),
        CharEntry("蕾珂丝", listOf("蕾珂丝", "Lux")),
        CharEntry("米利欧", listOf("米利欧", "Millio")),
        CharEntry("娜美", listOf("娜美", "Nami")),
        CharEntry("索拉卡", listOf("索拉卡", "Soraka", "星妈")),
        CharEntry("迦娜", listOf("迦娜", "Janna", "风女")),
        CharEntry("璐璐", listOf("璐璐", "Lulu")),
        CharEntry("塔莉垭", listOf("塔莉垭", "Taliyah", "岩雀")),
        CharEntry("奇亚娜", listOf("奇亚娜", "Qiyana")),
        CharEntry("伊泽瑞尔", listOf("伊泽瑞尔", "Ezreal", "EZ"))
    )),
    SourceGroup("崩坏 星穹铁道", listOf("崩坏 星穹铁道", "崩坏星穹铁道", "Honkai Star Rail", "星铁", "星穹铁道", "HSR"), listOf(
        CharEntry("卡芙卡", listOf("卡芙卡", "Kafka")),
        CharEntry("银狼", listOf("银狼", "Silver Wolf")),
        CharEntry("布洛妮娅", listOf("布洛妮娅", "Bronya")),
        CharEntry("希儿", listOf("希儿", "Seele")),
        CharEntry("姬子", listOf("姬子", "Himeko")),
        CharEntry("黑塔", listOf("黑塔", "Herta")),
        CharEntry("青雀", listOf("青雀", "Qingque")),
        CharEntry("符玄", listOf("符玄", "Fu Xuan")),
        CharEntry("托帕", listOf("托帕", "Topaz")),
        CharEntry("桂乃芬", listOf("桂乃芬", "Guinaifen")),
        CharEntry("藿藿", listOf("藿藿", "HuoHuo")),
        CharEntry("阮梅", listOf("阮梅", "Ruan Mei")),
        CharEntry("花火", listOf("花火", "Sparkle")),
        CharEntry("黄泉", listOf("黄泉", "Acheron")),
        CharEntry("知更鸟", listOf("知更鸟", "Robin")),
        CharEntry("流萤", listOf("流萤", "Firefly")),
        CharEntry("翡翠", listOf("翡翠", "Jade")),
        CharEntry("云璃", listOf("云璃", "Yunli")),
        CharEntry("椒丘", listOf("椒丘", "Jiaoqiu")),
        CharEntry("飞霄", listOf("飞霄", "Feixiao")),
        CharEntry("灵砂", listOf("灵砂", "Lingsha")),
        CharEntry("停云", listOf("停云", "Tingyun")),
        CharEntry("素裳", listOf("素裳", "Sushang")),
        CharEntry("虎克", listOf("虎克", "Hook")),
        CharEntry("克拉拉", listOf("克拉拉", "Clara")),
        CharEntry("娜塔莎", listOf("娜塔莎", "Natasha")),
        CharEntry("佩拉", listOf("佩拉", "Pela")),
        CharEntry("玲可", listOf("玲可", "Lynx")),
        CharEntry("白露", listOf("白露", "Bailu")),
        CharEntry("镜流", listOf("镜流", "Jingliu")),
        CharEntry("三月七", listOf("三月七", "March 7th", "三七")),
        CharEntry("开拓者", listOf("开拓者", "Trailblazer", "星", "穹")),
        CharEntry("昔涟", listOf("昔涟")),
        CharEntry("海瑟音", listOf("海瑟音")),
        CharEntry("遐蝶", listOf("遐蝶")),
        CharEntry("玄符", listOf("玄符"))
    )),
    SourceGroup("崩坏3", listOf("崩坏3", "崩坏3rd", "崩坏3rd", "Honkai Impact 3rd", "崩坏三"), listOf(
        CharEntry("琪亚娜", listOf("琪亚娜", "Kiana", "空之律者")),
        CharEntry("芽衣", listOf("芽衣", "Mei", "雷电芽衣")),
        CharEntry("布洛妮娅", listOf("布洛妮娅", "Bronya", "理之律者")),
        CharEntry("符华", listOf("符华", "Fu Hua", "凤凰")),
        CharEntry("丽塔", listOf("丽塔", "Rita")),
        CharEntry("幽兰黛尔", listOf("幽兰黛尔", "Durandal")),
        CharEntry("希儿", listOf("希儿", "Seele")),
        CharEntry("八重樱", listOf("八重樱", "Sakura", "Yae Sakura")),
        CharEntry("德丽莎", listOf("德丽莎", "Theresa")),
        CharEntry("爱莉希雅", listOf("爱莉希雅", "Elysia", "粉色妖精")),
        CharEntry("梅比乌斯", listOf("梅比乌斯", "Mobius", "蛇")),
        CharEntry("伊甸", listOf("伊甸", "Eden")),
        CharEntry("阿波尼亚", listOf("阿波尼亚", "Aponia")),
        CharEntry("千劫", listOf("千劫", "Kalpas")),
        CharEntry("华", listOf("华", "Hua")),
        CharEntry("渡鸦", listOf("渡鸦", "Raven")),
        CharEntry("萝莎莉娅", listOf("萝莎莉娅", "Rozaliya")),
        CharEntry("莉莉娅", listOf("莉莉娅", "Liliya")),
        CharEntry("瑟利姆", listOf("瑟利姆", "Selim"))
    )),
    SourceGroup("原神", listOf("原神", "Genshin Impact", "Genshin", "原"), listOf(
        CharEntry("甘雨", listOf("甘雨", "Ganyu", "椰羊")),
        CharEntry("胡桃", listOf("胡桃", "Hu Tao", "堂主")),
        CharEntry("雷电将军", listOf("雷电将军", "雷神", "Raiden Shogun", "影", "Ei")),
        CharEntry("神里绫华", listOf("神里绫华", "绫华", "Ayaka", "白鹭公主")),
        CharEntry("宵宫", listOf("宵宫", "Yoimiya")),
        CharEntry("八重神子", listOf("八重神子", "神子", "Yae Miko", "狐狸")),
        CharEntry("珊瑚宫心海", listOf("珊瑚宫心海", "心海", "Kokomi", "军师")),
        CharEntry("申鹤", listOf("申鹤", "Shenhe")),
        CharEntry("夜兰", listOf("夜兰", "Yelan")),
        CharEntry("妮露", listOf("妮露", "Nilou")),
        CharEntry("纳西妲", listOf("纳西妲", "Nahida", "草神", "小吉祥草王")),
        CharEntry("优菈", listOf("优菈", "Eula", "浪花骑士")),
        CharEntry("刻晴", listOf("刻晴", "Keqing", "玉衡星")),
        CharEntry("凝光", listOf("凝光", "Ningguang", "天权星")),
        CharEntry("北斗", listOf("北斗", "Beidou")),
        CharEntry("丽莎", listOf("丽莎", "Lisa")),
        CharEntry("安柏", listOf("安柏", "Amber")),
        CharEntry("芭芭拉", listOf("芭芭拉", "Barbara", "牧师")),
        CharEntry("琴", listOf("琴", "Jean", "代理团长")),
        CharEntry("莫娜", listOf("莫娜", "Mona", "占星术士")),
        CharEntry("菲谢尔", listOf("菲谢尔", "Fischl", "皇女")),
        CharEntry("诺艾尔", listOf("诺艾尔", "Noelle", "女仆")),
        CharEntry("香菱", listOf("香菱", "Xiangling")),
        CharEntry("行秋", listOf("行秋", "Xingqiu")),
        CharEntry("荧", listOf("荧", "Lumine", "妹妹")),
        CharEntry("罗莎莉亚", listOf("罗莎莉亚", "Rosaria", "修女")),
        CharEntry("烟绯", listOf("烟绯", "Yanfei")),
        CharEntry("辛焱", listOf("辛焱", "Xinyan")),
        CharEntry("云堇", listOf("云堇", "Yun Jin")),
        CharEntry("久岐忍", listOf("久岐忍", "Shinobu")),
        CharEntry("鹿野院平藏", listOf("鹿野院平藏", "平藏", "Heizou")),
        CharEntry("柯莱", listOf("柯莱", "Collei")),
        CharEntry("多莉", listOf("多莉", "Dori")),
        CharEntry("坎蒂丝", listOf("坎蒂丝", "Candace")),
        CharEntry("莱依拉", listOf("莱依拉", "Layla")),
        CharEntry("珐露珊", listOf("珐露珊", "Faruzan")),
        CharEntry("迪希雅", listOf("迪希雅", "Dehya")),
        CharEntry("米卡", listOf("米卡", "Mika")),
        CharEntry("白术", listOf("白术", "Baizhu")),
        CharEntry("绮良良", listOf("绮良良", "Kirara")),
        CharEntry("芙宁娜", listOf("芙宁娜", "Furina", "水神")),
        CharEntry("夏洛蒂", listOf("夏洛蒂", "Charlotte")),
        CharEntry("娜维娅", listOf("娜维娅", "Navia")),
        CharEntry("夏沃蕾", listOf("夏沃蕾", "Chevreuse")),
        CharEntry("闲云", listOf("闲云", "Xianyun", "留云借风真君")),
        CharEntry("嘉明", listOf("嘉明", "Gaming")),
        CharEntry("千织", listOf("千织", "Chiori")),
        CharEntry("阿蕾奇诺", listOf("阿蕾奇诺", "Arlecchino", "仆人", "父亲")),
        CharEntry("希格雯", listOf("希格雯", "Sigewinne", "护士长")),
        CharEntry("克洛琳德", listOf("克洛琳德", "Clorinde")),
        CharEntry("艾梅莉埃", listOf("艾梅莉埃", "Emilie")),
        CharEntry("玛拉妮", listOf("玛拉妮", "Mualani")),
        CharEntry("希诺宁", listOf("希诺宁", "Xilonen")),
        CharEntry("基尼奇", listOf("基尼奇", "Kinich")),
        CharEntry("卡齐娜", listOf("卡齐娜", "Kachina")),
        CharEntry("欧洛伦", listOf("欧洛伦", "Ororon")),
        CharEntry("茜特菈莉", listOf("茜特菈莉", "Citlali")),
        CharEntry("蓝砚", listOf("蓝砚", "Lanyan")),
        CharEntry("瓦莱丽", listOf("瓦莱丽", "Varesa"))
    )),
    SourceGroup("赛博朋克2077", listOf("赛博朋克2077", "赛博朋克 2077", "2077", "Cyberpunk 2077", "Cyberpunk", "赛博朋克"), listOf(
        CharEntry("帕南", listOf("帕南", "Panam")),
        CharEntry("朱迪", listOf("朱迪", "Judy")),
        CharEntry("罗格", listOf("罗格", "Rogue")),
        CharEntry("梅瑞德斯", listOf("梅瑞德斯", "Meredith")),
        CharEntry("艾芙琳", listOf("艾芙琳", "Evelyn")),
        CharEntry("T Bug", listOf("T Bug", "T-Bug")),
        CharEntry("华子", listOf("华子", "Hanako")),
        CharEntry("克里", listOf("克里", "Kerry")),
        CharEntry("米丝蒂", listOf("米丝蒂", "Misty"))
    )),
    SourceGroup("最终幻想", listOf("最终幻想7 重制版", "最终幻想7", "最终幻想 7", "最终幻想16", "最终幻想15", "最终幻想14", "最终幻想", "Final Fantasy", "FF7", "FF14", "FF16", "FF15"), listOf(
        CharEntry("蒂法", listOf("蒂法", "Tifa", "蒂法洛克哈特")),
        CharEntry("爱丽丝", listOf("爱丽丝", "Aerith", "艾瑞丝", "爱丽丝盖恩斯巴勒")),
        CharEntry("尤菲", listOf("尤菲", "Yuffie", "如月尤菲")),
        CharEntry("吉尔", listOf("吉尔", "Jill")),
        CharEntry("蕾菲娅", listOf("蕾菲娅", "Refia")),
        CharEntry("莉诺亚", listOf("莉诺亚", "Rinoa")),
        CharEntry("塞拉", listOf("塞拉", "Serah")),
        CharEntry("雷霆", listOf("雷霆", "Lightning", "克莱尔")),
        CharEntry("露娜弗蕾亚", listOf("露娜弗蕾亚", "Lunafreya", "露娜")),
        CharEntry("尤娜", listOf("尤娜", "Yuna")),
        CharEntry("莉库", listOf("莉库", "Rikku")),
        CharEntry("帕茵", listOf("帕茵", "Paine")),
        CharEntry("阿什", listOf("阿什", "Ashe")),
        CharEntry("梵妮尔", listOf("梵妮尔", "Vanille")),
        CharEntry("牙", listOf("牙", "Fang")),
        CharEntry("塞拉", listOf("塞拉", "Celes")),
        CharEntry("蒂娜", listOf("蒂娜", "Terra")),
        CharEntry("法丽斯", listOf("法丽斯", "Faris")),
        CharEntry("蕾娜", listOf("蕾娜", "Lenna")),
        CharEntry("嘉源", listOf("嘉源", "Rydia")),
        CharEntry("罗莎", listOf("罗莎", "Rosa")),
        CharEntry("艾蔻", listOf("艾蔻", "Echo")),
        CharEntry("克劳德", listOf("克劳德", "Cloud")),
        CharEntry("萨菲罗斯", listOf("萨菲罗斯", "Sephiroth")),
        CharEntry("甘蒂亚娜", listOf("甘蒂亚娜", "吉恩提亚娜", "Gentiana"))
    )),
    SourceGroup("艾尔登法环", listOf("艾尔登法环", "Elden Ring", "老头环"), listOf(
        CharEntry("玛丽卡", listOf("玛丽卡", "Marika", "永恒女王")),
        CharEntry("拉妮", listOf("拉妮", "Ranni", "雪魔女")),
        CharEntry("玛莲妮亚", listOf("玛莲妮亚", "玛莲妮娅", "Malenia", "米凯拉的锋刃", "女武神")),
        CharEntry("梅琳娜", listOf("梅琳娜", "Melina")),
        CharEntry("菈雅", listOf("菈雅", "Rya")),
        CharEntry("蕾娜拉", listOf("蕾娜拉", "Rennala")),
        CharEntry("瑟濂", listOf("瑟濂", "Sellen", "魔女")),
        CharEntry("拉特娜", listOf("拉特娜", "Latenna")),
        CharEntry("涅斐丽", listOf("涅斐丽", "Nepheli")),
        CharEntry("菲雅", listOf("菲雅", "Fia", "死眠少女")),
        CharEntry("海妲", listOf("海妲", "Hyetta")),
        CharEntry("伊蕾娜", listOf("伊蕾娜", "Irina")),
        CharEntry("托莉娜", listOf("托莉娜", "St Trina")),
        CharEntry("蕾达", listOf("蕾达", "Leda")),
        CharEntry("安帕赫", listOf("安帕赫", "Ansbach")),
        CharEntry("穆格", listOf("穆格", "Mohg"))
    )),
    SourceGroup("巫师", listOf("巫师3", "巫师 3", "The Witcher 3", "The Witcher", "巫师"), listOf(
        CharEntry("希里", listOf("希里", "Ciri", "辛特拉的幼狮")),
        CharEntry("叶奈法", listOf("叶奈法", "Yennefer", "叶姐")),
        CharEntry("特莉丝", listOf("特莉丝", "Triss")),
        CharEntry("凯拉", listOf("凯拉", "Keira")),
        CharEntry("夏妮", listOf("夏妮", "Shani")),
        CharEntry("普丽希拉", listOf("普丽希拉", "Priscilla")),
        CharEntry("安娜亨利叶塔", listOf("安娜亨利叶塔", "Anna Henrietta")),
        CharEntry("席安娜", listOf("席安娜", "Syanna")),
        CharEntry("芙琳吉拉", listOf("芙琳吉拉", "Fringilla")),
        CharEntry("芮娜", listOf("芮娜", "Renfri"))
    )),
    SourceGroup("生化危机", listOf("生化危机4 重制版", "生化危机4", "生化危机2 重制版", "生化危机2", "生化危机3", "生化危机8", "生化危机", "Resident Evil", "RE2", "RE4"), listOf(
        CharEntry("克莱尔", listOf("克莱尔", "Claire", "克莱尔雷德菲尔德")),
        CharEntry("吉尔", listOf("吉尔", "Jill", "吉尔瓦伦丁")),
        CharEntry("艾达", listOf("艾达", "Ada", "Ada Wong", "王艾达")),
        CharEntry("瑞贝卡", listOf("瑞贝卡", "Rebecca")),
        CharEntry("米娅", listOf("米娅", "Mia")),
        CharEntry("萝丝", listOf("萝丝", "Rose", "Rosemary")),
        CharEntry("蒂米特雷斯库", listOf("蒂米特雷斯库", "Lady Dimitrescu", "八尺大人", "吸血鬼夫人")),
        CharEntry("谢娃", listOf("谢娃", "Sheva")),
        CharEntry("海伦娜", listOf("海伦娜", "Helena")),
        CharEntry("格蕾丝", listOf("格蕾丝", "Grace")),
        CharEntry("雪莉", listOf("雪莉", "Sherry Birkin", "雪莉柏金", "Sherry")),
        CharEntry("艾什莉", listOf("艾什莉", "Ashley"))
    )),
    SourceGroup("古墓丽影", listOf("古墓丽影", "Tomb Raider"), listOf(
        CharEntry("劳拉", listOf("劳拉", "Lara", "Lara Croft", "劳拉克劳馥"))
    )),
    SourceGroup("博德之门3", listOf("博德之门3", "博德之门 3", "Baldurs Gate 3", "Baldurs Gate", "BG3"), listOf(
        CharEntry("影心", listOf("影心", "Shadowheart")),
        CharEntry("莱埃泽尔", listOf("莱埃泽尔", "Laezel")),
        CharEntry("卡尔赫", listOf("卡尔赫", "Karlach")),
        CharEntry("明萨拉", listOf("明萨拉", "Minthara"))
    )),
    SourceGroup("光与影 33号远征队", listOf("光与影 33号远征队", "光与影33号远征队", "Clair Obscur Expedition 33"), listOf(
        CharEntry("吕涅", listOf("吕涅", "Lune")),
        CharEntry("玛埃尔", listOf("玛埃尔", "Maelle")),
        CharEntry("希耶尔", listOf("希耶尔", "Sciel"))
    )),
    SourceGroup("剑星", listOf("剑星", "Stellar Blade"), listOf(
        CharEntry("伊芙", listOf("伊芙", "Eve")),
        CharEntry("塔奇", listOf("塔奇", "Tachy")),
        CharEntry("渡鸦", listOf("渡鸦", "Raven")),
        CharEntry("讯梓", listOf("讯梓", "Xunzi"))
    )),
    SourceGroup("铁拳", listOf("铁拳8", "铁拳7", "铁拳6", "铁拳5", "铁拳", "Tekken 8", "Tekken 7", "Tekken 6", "Tekken"), listOf(
        CharEntry("莉莉", listOf("莉莉", "Lili", "艾米莉德罗什福尔")),
        CharEntry("风间飞鸟", listOf("风间飞鸟", "飞鸟", "Xiaoyu", "凌晓雨")),
        CharEntry("妮娜", listOf("妮娜", "Nina", "妮娜威廉姆斯")),
        CharEntry("安娜", listOf("安娜", "Anna", "安娜威廉姆斯")),
        CharEntry("克里斯蒂", listOf("克里斯蒂", "Christie")),
        CharEntry("阿丽莎", listOf("阿丽莎", "Alisa")),
        CharEntry("幸运克洛伊", listOf("幸运克洛伊", "Lucky Chloe")),
        CharEntry("和真", listOf("和真", "Kazumi")),
        CharEntry("乔西", listOf("乔西", "Josie")),
        CharEntry("莉迪亚", listOf("莉迪亚", "Lidia")),
        CharEntry("卡塔琳娜", listOf("卡塔琳娜", "Katarina")),
        CharEntry("艾丽莎", listOf("艾丽莎", "Eliza")),
        CharEntry("莫妮卡", listOf("莫妮卡", "Monica")),
        CharEntry("州光", listOf("州光", "Kunimitsu")),
        CharEntry("阿苏塞娜", listOf("阿苏塞娜", "Azucena", "咖啡女王"))
    )),
    SourceGroup("恶魔战士", listOf("恶魔战士", "Darkstalkers", "Vampire Savior"), listOf(
        CharEntry("莫莉卡", listOf("莫莉卡", "Morrigan", "梦魔")),
        CharEntry("莉莉丝", listOf("莉莉丝", "Lilith")),
        CharEntry("菲莉西亚", listOf("菲莉西亚", "Felicia", "猫女")),
        CharEntry("恋", listOf("恋", "Hsien Ko", "中国僵尸")),
        CharEntry("Q Bee", listOf("Q Bee", "Q-Bee")),
        CharEntry("小红帽", listOf("小红帽", "B B Hood", "Bulleta"))
    )),
    SourceGroup("绝区零", listOf("绝区零", "Zenless Zone Zero", "ZZZ"), listOf(
        CharEntry("安比", listOf("安比", "Anby")),
        CharEntry("妮可", listOf("妮可", "Nicole")),
        CharEntry("猫又", listOf("猫又", "Nekomata", "猫宫又奈")),
        CharEntry("丽娜", listOf("丽娜", "Rina")),
        CharEntry("艾莲", listOf("艾莲", "Ellen", "艾莲乔")),
        CharEntry("朱鸢", listOf("朱鸢", "Zhu Yuan")),
        CharEntry("青衣", listOf("青衣", "Qingyi")),
        CharEntry("简", listOf("简", "Jane", "简杜")),
        CharEntry("凯撒", listOf("凯撒", "Caesar")),
        CharEntry("柏妮思", listOf("柏妮思", "Burnice")),
        CharEntry("柳", listOf("柳", "Yanagi")),
        CharEntry("星见雅", listOf("星见雅", "雅", "Hoshimi Miyabi", "Miyabi")),
        CharEntry("伊芙琳", listOf("伊芙琳", "Evelyn")),
        CharEntry("莱特", listOf("莱特", "Lighter")),
        CharEntry("悠真", listOf("悠真", "Harumasa")),
        CharEntry("耀嘉音", listOf("耀嘉音")),
        CharEntry("仪玄", listOf("仪玄")),
        CharEntry("叶瞬光", listOf("叶瞬光")),
        CharEntry("千夏", listOf("千夏", "Chinatsu"))
    )),
    SourceGroup("明日方舟", listOf("明日方舟", "Arknights", "方舟"), listOf(
        CharEntry("阿米娅", listOf("阿米娅", "Amiya")),
        CharEntry("凯尔希", listOf("凯尔希", "Kaltsit")),
        CharEntry("陈", listOf("陈", "Chen", "陈晖洁")),
        CharEntry("史尔特尔", listOf("史尔特尔", "Surtr")),
        CharEntry("W", listOf("W")),
        CharEntry("斯卡蒂", listOf("斯卡蒂", "Skadi", "蒂蒂")),
        CharEntry("幽灵鲨", listOf("幽灵鲨", "Specter")),
        CharEntry("塞雷娅", listOf("塞雷娅", "Saria")),
        CharEntry("推进之王", listOf("推进之王", "Siege")),
        CharEntry("德克萨斯", listOf("德克萨斯", "Texas", "得克萨斯")),
        CharEntry("拉普兰德", listOf("拉普兰德", "Lappland")),
        CharEntry("能天使", listOf("能天使", "Exusiai")),
        CharEntry("莫斯提马", listOf("莫斯提马", "Mostima")),
        CharEntry("安洁莉娜", listOf("安洁莉娜", "Angelina")),
        CharEntry("伊芙利特", listOf("伊芙利特", "Ifrit")),
        CharEntry("麦哲伦", listOf("麦哲伦", "Magallan")),
        CharEntry("临光", listOf("临光", "Nearl")),
        CharEntry("泥岩", listOf("泥岩", "Mudrock")),
        CharEntry("卡涅利安", listOf("卡涅利安", "Carnelian")),
        CharEntry("夕", listOf("夕", "Dusk")),
        CharEntry("令", listOf("令", "Ling")),
        CharEntry("山", listOf("山", "Shanhai")),
        CharEntry("琴柳", listOf("琴柳", "Saileach")),
        CharEntry("耀骑士临光", listOf("耀骑士临光", "Nearl the Radiant Knight")),
        CharEntry("瑕光", listOf("瑕光", "Blemishine")),
        CharEntry("迷迭香", listOf("迷迭香", "Rosmontis")),
        CharEntry("浊心斯卡蒂", listOf("浊心斯卡蒂")),
        CharEntry("红", listOf("红", "Projekt Red")),
        CharEntry("霜叶", listOf("霜叶", "Frostleaf")),
        CharEntry("芙兰卡", listOf("芙兰卡", "Franka")),
        CharEntry("崖心", listOf("崖心", "Cliffheart")),
        CharEntry("初雪", listOf("初雪", "Pramanix")),
        CharEntry("银灰", listOf("银灰", "SilverAsh")),
        CharEntry("灵知", listOf("灵知", "Gnosis")),
        CharEntry("司霆惊蛰", listOf("司霆惊蛰", "惊蛰")),
        CharEntry("特蕾西娅", listOf("特蕾西娅", "Theresa")),
        CharEntry("闪灵", listOf("闪灵", "Shining"))
    )),
    SourceGroup("碧蓝航线", listOf("碧蓝航线", "Azur Lane", "AL"), listOf(
        CharEntry("企业", listOf("企业", "Enterprise", "灰幽灵")),
        CharEntry("贝尔法斯特", listOf("贝尔法斯特", "Belfast", "贝法")),
        CharEntry("爱宕", listOf("爱宕", "Atago", "犬")),
        CharEntry("高雄", listOf("高雄", "Takao", "狼")),
        CharEntry("胡德", listOf("胡德", "Hood")),
        CharEntry("威尔士亲王", listOf("威尔士亲王", "Prince of Wales")),
        CharEntry("光辉", listOf("光辉", "Illustrious")),
        CharEntry("赤城", listOf("赤城", "Akagi")),
        CharEntry("加贺", listOf("加贺", "Kaga")),
        CharEntry("克利夫兰", listOf("克利夫兰", "Cleveland")),
        CharEntry("海伦娜", listOf("海伦娜", "Helena")),
        CharEntry("华盛顿", listOf("华盛顿", "Washington")),
        CharEntry("俾斯麦", listOf("俾斯麦", "Bismarck")),
        CharEntry("提尔比茨", listOf("提尔比茨", "Tirpitz")),
        CharEntry("齐柏林", listOf("齐柏林", "Graf Zeppelin")),
        CharEntry("罗恩", listOf("罗恩", "Roon")),
        CharEntry("腓特烈大帝", listOf("腓特烈大帝", "Friedrich der Grosse")),
        CharEntry("欧根亲王", listOf("欧根亲王", "Prinz Eugen")),
        CharEntry("独角兽", listOf("独角兽", "Unicorn")),
        CharEntry("圣地亚哥", listOf("圣地亚哥", "San Diego", "金坷垃")),
        CharEntry("天城", listOf("天城", "Amagi")),
        CharEntry("大凤", listOf("大凤", "Taihou")),
        CharEntry("皇家方舟", listOf("皇家方舟", "Ark Royal")),
        CharEntry("约克城", listOf("约克城", "Yorktown")),
        CharEntry("大黄蜂", listOf("大黄蜂", "Hornet")),
        CharEntry("女灶神", listOf("女灶神", "Vestal")),
        CharEntry("埃塞克斯", listOf("埃塞克斯", "Essex")),
        CharEntry("巴尔的摩", listOf("巴尔的摩", "Baltimore")),
        CharEntry("巴伐利亚", listOf("巴伐利亚", "Bayern")),
        CharEntry("泽西", listOf("泽西", "Jersey")),
        CharEntry("瑞吉娜", listOf("瑞吉娜", "Regina")),
        CharEntry("安克雷奇", listOf("安克雷奇", "Anchorage"))
    )),
    SourceGroup("碧蓝档案", listOf("碧蓝档案", "蔚蓝档案", "Blue Archive", "BA"), listOf(
        CharEntry("阿露", listOf("阿露", "Aru")),
        CharEntry("白子", listOf("白子", "Shiroko", "砂狼白子")),
        CharEntry("日奈", listOf("日奈", "Hina")),
        CharEntry("亚子", listOf("亚子", "Ako")),
        CharEntry("明日奈", listOf("明日奈", "Asuna")),
        CharEntry("花凛", listOf("花凛", "Karin")),
        CharEntry("妮露", listOf("妮露", "Neru")),
        CharEntry("时", listOf("时", "Toki")),
        CharEntry("妃雪", listOf("妃雪", "Kisaki")),
        CharEntry("未花", listOf("未花", "Mika")),
        CharEntry("渚", listOf("渚", "Nagisa")),
        CharEntry("真白", listOf("真白", "Miyako")),
        CharEntry("咲", listOf("咲", "Saki")),
        CharEntry("伊织", listOf("伊织", "Iori")),
        CharEntry("千夏", listOf("千夏", "Chinatsu")),
        CharEntry("绫音", listOf("绫音", "Ayane")),
        CharEntry("莲见", listOf("莲见", "Hasumi")),
        CharEntry("爱丽丝", listOf("爱丽丝", "Aris", "Alice")),
        CharEntry("椿", listOf("椿", "Tsubaki")),
        CharEntry("星野", listOf("星野", "Hoshino")),
        CharEntry("芹香", listOf("芹香", "Serika")),
        CharEntry("切里诺", listOf("切里诺", "Cherino")),
        CharEntry("泉", listOf("泉", "Izumi")),
        CharEntry("纯子", listOf("纯子", "Junko")),
        CharEntry("晴", listOf("晴", "Hare")),
        CharEntry("小雪", listOf("小雪", "Koyuki")),
        CharEntry("若叶", listOf("若叶", "Wakamo")),
        CharEntry("阿兹莎", listOf("阿兹莎", "Azusa")),
        CharEntry("优香", listOf("优香", "早濑优香", "Yuuka")),
        CharEntry("调月莉音", listOf("调月莉音", "Tsurumaki Tsukasa"))
    )),
    SourceGroup("胜利女神 NIKEE", listOf("胜利女神 NIKEE", "NIKEE", "胜利女神", "Goddess of Victory Nikke", "Nikke", "妮姬"), listOf(
        CharEntry("拉毗", listOf("拉毗", "Rapi")),
        CharEntry("阿尼斯", listOf("阿尼斯", "Anis")),
        CharEntry("妮恩", listOf("妮恩", "Neon")),
        CharEntry("玛丽安", listOf("玛丽安", "Marian")),
        CharEntry("爱丽丝", listOf("爱丽丝", "Alice")),
        CharEntry("迪塞尔", listOf("迪塞尔", "Diesel")),
        CharEntry("艾玛", listOf("艾玛", "Emma")),
        CharEntry("维斯提", listOf("维斯提", "Vesti")),
        CharEntry("银华", listOf("银华", "Eunhwa")),
        CharEntry("露菲", listOf("露菲", "Rupee")),
        CharEntry("安", listOf("安", "Anne")),
        CharEntry("玛丽", listOf("玛丽", "Mary")),
        CharEntry("佩珀", listOf("佩珀", "Pepper")),
        CharEntry("舒格", listOf("舒格", "Sugar")),
        CharEntry("米尔克", listOf("米尔克", "Milk")),
        CharEntry("沃尔姆", listOf("沃尔姆", "Volume")),
        CharEntry("吉尔蒂", listOf("吉尔蒂", "Guilty")),
        CharEntry("辛", listOf("辛", "Sin")),
        CharEntry("赫尔姆", listOf("赫尔姆", "Helm")),
        CharEntry("马斯塔", listOf("马斯塔", "Mast")),
        CharEntry("安克", listOf("安克", "Anchor")),
        CharEntry("布丽德", listOf("布丽德", "Brid")),
        CharEntry("红莲", listOf("红莲", "Scarlet")),
        CharEntry("长发公主", listOf("长发公主", "Rapunzel")),
        CharEntry("白雪公主", listOf("白雪公主", "Snow White")),
        CharEntry("玫瑰", listOf("玫瑰", "Rose")),
        CharEntry("白", listOf("白", "Weiss")),
        CharEntry("黑", listOf("黑", "Noir")),
        CharEntry("小红帽", listOf("小红帽", "Red Hood")),
        CharEntry("王冠", listOf("王冠", "Crown")),
        CharEntry("铃铛", listOf("铃铛", "Chime")),
        CharEntry("娜迦", listOf("娜迦", "Naga")),
        CharEntry("提亚", listOf("提亚", "Tia")),
        CharEntry("D", listOf("D")),
        CharEntry("K", listOf("K")),
        CharEntry("艾莉格", listOf("艾莉格", "Elegg")),
        CharEntry("樱花", listOf("樱花", "Sakura")),
        CharEntry("罗莎娜", listOf("罗莎娜", "Rosanna")),
        CharEntry("莫兰", listOf("莫兰", "Moran")),
        CharEntry("多萝西", listOf("多萝西", "Dorothy")),
        CharEntry("哈兰", listOf("哈兰", "Harran")),
        CharEntry("伊莎贝尔", listOf("伊莎贝尔", "Isabel")),
        CharEntry("诺亚", listOf("诺亚", "Noah")),
        CharEntry("现代者", listOf("现代者", "Modernia")),
        CharEntry("虚无者", listOf("虚无者", "Nihilister")),
        CharEntry("灰姑娘", listOf("灰姑娘", "Cinderella"))
    )),
    SourceGroup("鸣潮", listOf("鸣潮", "Wuthering Waves", "WW"), listOf(
        CharEntry("秧秧", listOf("秧秧", "Yangyang")),
        CharEntry("赤霞", listOf("赤霞", "Chixia")),
        CharEntry("白芷", listOf("白芷", "Baizhi")),
        CharEntry("吟霖", listOf("吟霖", "Yinlin")),
        CharEntry("鉴心", listOf("鉴心", "Jianxin")),
        CharEntry("安可", listOf("安可", "Encore")),
        CharEntry("散华", listOf("散华", "Sanhua")),
        CharEntry("丹瑾", listOf("丹瑾", "Danjin")),
        CharEntry("卡梅莉亚", listOf("卡梅莉亚", "Camellya")),
        CharEntry("灯灯", listOf("灯灯", "Lumi")),
        CharEntry("桃祈", listOf("桃祈", "Taoqi")),
        CharEntry("釉瑚", listOf("釉瑚", "Youhu")),
        CharEntry("折枝", listOf("折枝", "Zhezhi")),
        CharEntry("守岸人", listOf("守岸人", "Shorekeeper")),
        CharEntry("卡洛塔", listOf("卡洛塔", "Carlotta")),
        CharEntry("罗西亚", listOf("罗西亚", "Roccia")),
        CharEntry("坎塔蕾拉", listOf("坎塔蕾拉", "Cantarella")),
        CharEntry("长离", listOf("长离", "Changli")),
        CharEntry("千咲", listOf("千咲", "Chisato")),
        CharEntry("夏空", listOf("夏空")),
        CharEntry("尤诺", listOf("尤诺")),
        CharEntry("西格莉卡", listOf("西格莉卡")),
        CharEntry("卡提希娅", listOf("卡提希娅")),
        CharEntry("露帕", listOf("露帕")),
        CharEntry("珂莱塔", listOf("珂莱塔", "Carlotta Montelli")),
        CharEntry("菲比", listOf("菲比", "Phoebe"))
    )),
    SourceGroup("战双帕弥什", listOf("战双帕弥什", "Punishing Gray Raven", "PGR"), listOf(
        CharEntry("露西亚", listOf("露西亚", "Lucia")),
        CharEntry("丽芙", listOf("丽芙", "Liv")),
        CharEntry("七实", listOf("七实", "Nanami")),
        CharEntry("卡列尼娜", listOf("卡列尼娜", "Karenina")),
        CharEntry("比安卡", listOf("比安卡", "Bianca")),
        CharEntry("艾丽莎", listOf("艾丽莎", "Alisa")),
        CharEntry("罗塞塔", listOf("罗塞塔", "Rosetta")),
        CharEntry("苏菲亚", listOf("苏菲亚", "Sophia")),
        CharEntry("薇拉", listOf("薇拉", "Vera")),
        CharEntry("曲", listOf("曲", "Qu")),
        CharEntry("蒲牢", listOf("蒲牢", "Pulao")),
        CharEntry("露娜", listOf("露娜", "Luna")),
        CharEntry("塞琳娜", listOf("塞琳娜", "Selena")),
        CharEntry("21号", listOf("21号", "No 21")),
        CharEntry("万世", listOf("万世", "Wanshi")),
        CharEntry("艾拉", listOf("艾拉", "Ayla")),
        CharEntry("邦比娜塔", listOf("邦比娜塔", "Bambinata")),
        CharEntry("亚里莎", listOf("亚里莎", "Arisa"))
    )),
    SourceGroup("少女前线", listOf("少女前线", "Girls Frontline", "GFL", "少前"), listOf(
        CharEntry("M4A1", listOf("M4A1")),
        CharEntry("AR15", listOf("AR15", "AR-15")),
        CharEntry("M16A1", listOf("M16A1")),
        CharEntry("SOPMOD2", listOf("SOPMOD2", "SOPMOD II", "狗子")),
        CharEntry("UMP45", listOf("UMP45", "45")),
        CharEntry("UMP9", listOf("UMP9", "9")),
        CharEntry("HK416", listOf("HK416", "416")),
        CharEntry("WA2000", listOf("WA2000", "WA")),
        CharEntry("春田", listOf("春田", "Springfield")),
        CharEntry("DSR50", listOf("DSR50", "DSR-50")),
        CharEntry("M200", listOf("M200")),
        CharEntry("AN94", listOf("AN94", "AN-94")),
        CharEntry("AK12", listOf("AK12", "AK-12")),
        CharEntry("RPK16", listOf("RPK16", "RPK-16")),
        CharEntry("雷电", listOf("雷电", "Thunder")),
        CharEntry("竞争者", listOf("竞争者", "Contender")),
        CharEntry("李恩菲尔德", listOf("李恩菲尔德", "Lee-Enfield")),
        CharEntry("莫辛纳甘", listOf("莫辛纳甘", "Mosin-Nagat")),
        CharEntry("SVD", listOf("SVD")),
        CharEntry("PPK", listOf("PPK")),
        CharEntry("M1911", listOf("M1911")),
        CharEntry("丹德莱", listOf("丹德莱", "Dandelion")),
        CharEntry("M4 SOPMOD II", listOf("M4 SOPMOD II"))
    )),
    SourceGroup("无期迷途", listOf("无期迷途", "Path to Nowhere", "PtN"), listOf(
        CharEntry("沙利叶", listOf("沙利叶", "Shalom")),
        CharEntry("卓雅", listOf("卓雅", "Zoya")),
        CharEntry("赫卡忒", listOf("赫卡忒", "Hecate")),
        CharEntry("爱丽妮", listOf("爱丽妮", "Eirene")),
        CharEntry("渡鸦", listOf("渡鸦", "Raven")),
        CharEntry("德蕾雅", listOf("德蕾雅", "Dreya")),
        CharEntry("观星者", listOf("观星者", "Stargazer")),
        CharEntry("阿黛拉", listOf("阿黛拉", "Adela")),
        CharEntry("白逸", listOf("白逸", "Baiyi")),
        CharEntry("伊琳娜", listOf("伊琳娜", "Irina")),
        CharEntry("麦昆", listOf("麦昆", "McQueen")),
        CharEntry("恩菲尔", listOf("恩菲尔", "Enfer")),
        CharEntry("可可莉克", listOf("可可莉克", "Coquelic")),
        CharEntry("瑟琳", listOf("瑟琳", "Shalom")),
        CharEntry("雷比尼斯", listOf("雷比尼斯", "Labyrinth")),
        CharEntry("佩姬", listOf("佩姬", "Pearl")),
        CharEntry("卡门", listOf("卡门", "Carmen")),
        CharEntry("兰利", listOf("兰利", "Langley")),
        CharEntry("哈梅尔", listOf("哈梅尔", "Hamel")),
        CharEntry("黛伦", listOf("黛伦", "Deren")),
        CharEntry("安", listOf("安", "Anne"))
    )),
    SourceGroup("尘白禁区", listOf("尘白禁区", "Snowbreak"), listOf(
        CharEntry("里芙", listOf("里芙", "Lyris")),
        CharEntry("芬妮", listOf("芬妮", "Fenny")),
        CharEntry("瑟瑞斯", listOf("瑟瑞斯", "Siris")),
        CharEntry("茉莉安", listOf("茉莉安", "Mauxir")),
        CharEntry("卡提娅", listOf("卡提娅", "Katya")),
        CharEntry("瑶", listOf("瑶", "Yao")),
        CharEntry("凌", listOf("凌", "Ling")),
        CharEntry("辰", listOf("辰", "Chen")),
        CharEntry("玛利亚", listOf("玛利亚", "Marian")),
        CharEntry("妮塔", listOf("妮塔", "Nita")),
        CharEntry("恩雅", listOf("恩雅", "Enya")),
        CharEntry("阿克娅", listOf("阿克娅", "Acacia")),
        CharEntry("苔丝", listOf("苔丝", "Tess")),
        CharEntry("晴", listOf("晴", "Haru"))
    )),
    SourceGroup("千年之旅", listOf("千年之旅", "Aether Gazer"), listOf(
        CharEntry("波塞冬", listOf("波塞冬", "Poseidon")),
        CharEntry("雅典娜", listOf("雅典娜", "Athena")),
        CharEntry("赫拉", listOf("赫拉", "Hera")),
        CharEntry("阿尔忒弥斯", listOf("阿尔忒弥斯", "Artemis")),
        CharEntry("天照", listOf("天照", "Amaterasu")),
        CharEntry("月读", listOf("月读", "Tsukuyomi")),
        CharEntry("女娲", listOf("女娲", "Nuwa")),
        CharEntry("书", listOf("书", "Shu")),
        CharEntry("赫利俄斯", listOf("赫利俄斯", "Hel"))
    )),
    SourceGroup("白夜极光", listOf("白夜极光", "Alchemy Stars"), listOf(
        CharEntry("维多利亚", listOf("维多利亚", "Victoria")),
        CharEntry("伊芙", listOf("伊芙", "Eve")),
        CharEntry("拉斐尔", listOf("拉斐尔", "Raphael")),
        CharEntry("绯螺", listOf("绯螺", "Hiiro")),
        CharEntry("奥菲娜", listOf("奥菲娜", "Ophina")),
        CharEntry("蕾奥娜", listOf("蕾奥娜", "Leona"))
    )),
    SourceGroup("阴阳师", listOf("阴阳师", "Onmyoji"), listOf(
        CharEntry("不知火", listOf("不知火", "Shiranui")),
        CharEntry("妖刀姬", listOf("妖刀姬", "Yoto Hime")),
        CharEntry("姑获鸟", listOf("姑获鸟", "Ubume")),
        CharEntry("青行灯", listOf("青行灯", "Aooni")),
        CharEntry("辉夜姬", listOf("辉夜姬", "Kaguyahime")),
        CharEntry("玉藻前", listOf("玉藻前", "Tamamo no Mae", "大舅妈")),
        CharEntry("鬼切", listOf("鬼切", "Onikiri")),
        CharEntry("铃鹿御前", listOf("铃鹿御前", "Suzuka Gozen")),
        CharEntry("紧那罗", listOf("紧那罗", "Kinnara")),
        CharEntry("帝释天", listOf("帝释天", "Taishakuten")),
        CharEntry("阿修罗", listOf("阿修罗", "Asura")),
        CharEntry("千姬", listOf("千姬", "Senhime")),
        CharEntry("缘结神", listOf("缘结神", "Musubi")),
        CharEntry("食灵", listOf("食灵", "Shokurei")),
        CharEntry("雪女", listOf("雪女", "Yuki Onna")),
        CharEntry("清姬", listOf("清姬", "Kiyohime")),
        CharEntry("红叶", listOf("红叶", "Momiji")),
        CharEntry("面灵气", listOf("面灵气", "Menreiki")),
        CharEntry("大天狗", listOf("大天狗", "Ootengu")),
        CharEntry("酒吞童子", listOf("酒吞童子", "Shuten Doji")),
        CharEntry("茨木童子", listOf("茨木童子", "Ibaraki Doji"))
    )),
    SourceGroup("第五人格", listOf("第五人格", "Identity V"), listOf(
        CharEntry("特蕾西", listOf("特蕾西", "Tracy", "机械师")),
        CharEntry("艾玛", listOf("艾玛", "Emma", "园丁")),
        CharEntry("玛尔塔", listOf("玛尔塔", "Martha", "空军")),
        CharEntry("海伦娜", listOf("海伦娜", "Helena", "盲女")),
        CharEntry("薇拉", listOf("薇拉", "Vera", "调香师")),
        CharEntry("帕特丽夏", listOf("帕特丽夏", "Patricia", "祭司")),
        CharEntry("莉莉", listOf("莉莉", "Lily", "入殓师")),
        CharEntry("黛米", listOf("黛米", "Demi", "调酒师")),
        CharEntry("艾达", listOf("艾达", "Ada", "心理学家")),
        CharEntry("艾米丽", listOf("艾米丽", "Emily", "医生")),
        CharEntry("菲欧娜", listOf("菲欧娜", "Fiona", "祭司")),
        CharEntry("玛格丽莎", listOf("玛格丽莎", "Margaretha", "舞女"))
    )),
    SourceGroup("永劫无间", listOf("永劫无间", "Naraka Bladepoint"), listOf(
        CharEntry("宁红夜", listOf("宁红夜", "Viper Ning")),
        CharEntry("胡桃", listOf("胡桃", "Kurumi")),
        CharEntry("迦南", listOf("迦南", "Canaan")),
        CharEntry("季沧海", listOf("季沧海", "Tarka Ji")),
        CharEntry("天海", listOf("天海", "Tianhai")),
        CharEntry("妖刀姬", listOf("妖刀姬", "Yoto Hime")),
        CharEntry("崔三娘", listOf("崔三娘", "Valda Cui")),
        CharEntry("顾清寒", listOf("顾清寒", "Justina Gu")),
        CharEntry("武运", listOf("武运", "Wuchen")),
        CharEntry("阴佩真", listOf("阴佩真", "Ziping Yin")),
        CharEntry("席拉", listOf("席拉", "Tessa"))
    )),
    SourceGroup("幻塔", listOf("幻塔", "Tower of Fantasy", "TOF"), listOf(
        CharEntry("奈美西斯", listOf("奈美西斯", "Nemesis")),
        CharEntry("钴蓝", listOf("钴蓝", "Cobalt B")),
        CharEntry("克劳迪娅", listOf("克劳迪娅", "Claudia")),
        CharEntry("弗丽嘉", listOf("弗丽嘉", "Frigg")),
        CharEntry("莱茵", listOf("莱茵", "Lyra")),
        CharEntry("红莲", listOf("红莲", "Ruby")),
        CharEntry("凛夜", listOf("凛夜", "Saki Fuwa")),
        CharEntry("琳", listOf("琳", "Lin")),
        CharEntry("安娜贝拉", listOf("安娜贝拉", "Annabella")),
        CharEntry("伊卡洛斯", listOf("伊卡洛斯", "Icarus")),
        CharEntry("天琅", listOf("天琅", "Tianlang")),
        CharEntry("乌米", listOf("乌米", "Umi")),
        CharEntry("菲欧娜", listOf("菲欧娜", "Fiona")),
        CharEntry("格温", listOf("格温", "Gwen")),
        CharEntry("白凌", listOf("白凌", "Bai Ling")),
        CharEntry("梅丽尔", listOf("梅丽尔", "Meryl")),
        CharEntry("赛弥尔", listOf("赛弥尔", "Samir")),
        CharEntry("修玛", listOf("修玛", "Huma")),
        CharEntry("可可丽特", listOf("可可丽特", "Cocoritter")),
        CharEntry("零", listOf("零", "Zero")),
        CharEntry("希尔达", listOf("希尔达", "Hilda")),
        CharEntry("佩佩", listOf("佩佩", "Pepper"))
    )),
    SourceGroup("Fate Grand Order", listOf("Fate Grand Order", "Fate GO", "FGO", "Fate"), listOf(
        CharEntry("阿尔托莉雅", listOf("阿尔托莉雅", "Artoria", "Saber", "呆毛王", "亚瑟王")),
        CharEntry("贞德", listOf("贞德", "Jeanne", "圣女")),
        CharEntry("斯卡哈", listOf("斯卡哈", "Scathach", "师匠")),
        CharEntry("玉藻前", listOf("玉藻前", "Tamamo", "Caster", "狐狸")),
        CharEntry("源赖光", listOf("源赖光", "Raikou", "乳光")),
        CharEntry("宫本武藏", listOf("宫本武藏", "Musashi")),
        CharEntry("冲田总司", listOf("冲田总司", "Okita")),
        CharEntry("织田信长", listOf("织田信长", "Nobunaga", "信长")),
        CharEntry("溶解莉莉丝", listOf("溶解莉莉丝", "Meltlilith", "Melt")),
        CharEntry("热情迷唇", listOf("热情迷唇", "Passionlip", "Lip")),
        CharEntry("BB", listOf("BB")),
        CharEntry("伊什塔尔", listOf("伊什塔尔", "Ishtar", "远坂凛")),
        CharEntry("埃列什基伽勒", listOf("埃列什基伽勒", "Ereshkigal", "艾蕾")),
        CharEntry("魁札尔科亚特尔", listOf("魁札尔科亚特尔", "Quetzalcoatl")),
        CharEntry("梅芙", listOf("梅芙", "Medb")),
        CharEntry("布狄卡", listOf("布狄卡", "Boudica")),
        CharEntry("玛塔哈丽", listOf("玛塔哈丽", "Mata Hari")),
        CharEntry("尼禄", listOf("尼禄", "Nero", "赤Saber")),
        CharEntry("伊丽莎白", listOf("伊丽莎白", "Elizabeth")),
        CharEntry("美杜莎", listOf("美杜莎", "Medusa", "Rider")),
        CharEntry("戈尔贡", listOf("戈尔贡", "Gorgon")),
        CharEntry("安娜", listOf("安娜", "Ana")),
        CharEntry("紫式部", listOf("紫式部", "Murasaki")),
        CharEntry("清少纳言", listOf("清少纳言", "Sei Shonagon")),
        CharEntry("杨贵妃", listOf("杨贵妃", "Yang Guifei")),
        CharEntry("虞美人", listOf("虞美人", "Yu Miaoyi")),
        CharEntry("燕青", listOf("燕青", "Qin Liangyu")),
        CharEntry("加雷斯", listOf("加雷斯", "Gareth")),
        CharEntry("阿比盖尔", listOf("阿比盖尔", "Abigail")),
        CharEntry("赛蕾娜", listOf("赛蕾娜", "Sitonai")),
        CharEntry("太空伊什塔尔", listOf("太空伊什塔尔", "Space Ishtar")),
        CharEntry("奥德修斯", listOf("奥德修斯", "Odysseus"))
    )),
    SourceGroup("Fate Stay Night", listOf("Fate Stay Night", "FSN"), listOf(
        CharEntry("Saber", listOf("Saber", "阿尔托莉雅", "Artoria", "呆毛")),
        CharEntry("远坂凛", listOf("远坂凛", "Rin", "凛")),
        CharEntry("间桐樱", listOf("间桐樱", "Sakura", "樱")),
        CharEntry("伊莉雅", listOf("伊莉雅", "Illya", "伊莉雅斯菲尔")),
        CharEntry("Rider", listOf("Rider", "美杜莎", "Medusa")),
        CharEntry("Caster", listOf("Caster", "美狄亚", "Medea")),
        CharEntry("藤村大河", listOf("藤村大河", "Taiga", "老虎"))
    )),
    SourceGroup("Fate Zero", listOf("Fate Zero"), listOf(
        CharEntry("爱丽丝菲尔", listOf("爱丽丝菲尔", "Irisviel", "切嗣太太")),
        CharEntry("索拉乌", listOf("索拉乌", "Sola Ui")),
        CharEntry("舞弥", listOf("舞弥", "Maiya"))
    )),
    SourceGroup("碧蓝幻想", listOf("碧蓝幻想", "Granblue Fantasy", "GBF"), listOf(
        CharEntry("姬塔", listOf("姬塔", "Djeeta")),
        CharEntry("卡塔莉娜", listOf("卡塔莉娜", "Katalina")),
        CharEntry("伊欧", listOf("伊欧", "Io")),
        CharEntry("露莉亚", listOf("露莉亚", "Lyria")),
        CharEntry("萝塞塔", listOf("萝塞塔", "Rosetta")),
        CharEntry("娜露梅", listOf("娜露梅", "Narumea")),
        CharEntry("尤艾尔", listOf("尤艾尔", "Yuel")),
        CharEntry("索希艾", listOf("索希艾", "Socie")),
        CharEntry("维拉", listOf("维拉", "Vira")),
        CharEntry("菲莉", listOf("菲莉", "Ferry")),
        CharEntry("贝阿特丽克斯", listOf("贝阿特丽克斯", "Beatrix")),
        CharEntry("泽塔", listOf("泽塔", "Zeta")),
        CharEntry("夏洛特", listOf("夏洛特", "Charlotta")),
        CharEntry("席尔瓦", listOf("席尔瓦", "Silva")),
        CharEntry("安", listOf("安", "Anne"))
    )),
    SourceGroup("公主连结", listOf("公主连结", "Princess Connect", "PCR", "公主连接"), listOf(
        CharEntry("佩可莉姆", listOf("佩可莉姆", "Pecorine", "吃货")),
        CharEntry("可可萝", listOf("可可萝", "Kokkoro")),
        CharEntry("凯留", listOf("凯留", "Kyaru", "凯露", "黑猫")),
        CharEntry("优衣", listOf("优衣", "Yui", "抖M")),
        CharEntry("日日莉", listOf("日日莉", "Hiyori")),
        CharEntry("怜", listOf("怜", "Rei")),
        CharEntry("栞", listOf("栞", "Shiori")),
        CharEntry("未奏希", listOf("未奏希", "Mitsuki")),
        CharEntry("莫妮卡", listOf("莫妮卡", "Monika")),
        CharEntry("纱织", listOf("纱织", "Saren")),
        CharEntry("望", listOf("望", "Nozomi")),
        CharEntry("千歌", listOf("千歌", "Chika")),
        CharEntry("真步", listOf("真步", "Mahomahu", "狐狸")),
        CharEntry("璃乃", listOf("璃乃", "Rino")),
        CharEntry("美里", listOf("美里", "Miri")),
        CharEntry("茜里", listOf("茜里", "Akari")),
        CharEntry("美美", listOf("美美", "Mimi")),
        CharEntry("露娜", listOf("露娜", "Luna")),
        CharEntry("克莉丝提娜", listOf("克莉丝提娜", "Christina")),
        CharEntry("杏奈", listOf("杏奈", "Anna"))
    )),
    SourceGroup("魔法纪录", listOf("魔法纪录", "Magia Record"), listOf(
        CharEntry("环伊吕波", listOf("环伊吕波", "Iroha")),
        CharEntry("七海八千代", listOf("七海八千代", "Yachiyo")),
        CharEntry("由比鹤乃", listOf("由比鹤乃", "Tsuruno")),
        CharEntry("二叶莎奈", listOf("二叶莎奈", "Sana")),
        CharEntry("深月菲莉希亚", listOf("深月菲莉希亚", "Felicia")),
        CharEntry("十咎桃子", listOf("十咎桃子", "Momoko"))
    )),
    SourceGroup("Apex Legends", listOf("Apex Legends", "Apex", "APEX"), listOf(
        CharEntry("萝芭", listOf("萝芭", "Loba")),
        CharEntry("沃特森", listOf("沃特森", "Wattson")),
        CharEntry("恶灵", listOf("恶灵", "Wraith")),
        CharEntry("班加罗尔", listOf("班加罗尔", "Bangalore")),
        CharEntry("催化姬", listOf("催化姬", "Catalyst")),
        CharEntry("瓦尔基里", listOf("瓦尔基里", "Valkyrie")),
        CharEntry("地平线", listOf("地平线", "Horizon")),
        CharEntry("疯玛吉", listOf("疯玛吉", "Mad Maggie")),
        CharEntry("万蒂奇", listOf("万蒂奇", "Vantage")),
        CharEntry("导线管", listOf("导线管", "Conduit")),
        CharEntry("生命线", listOf("生命线", "Lifeline")),
        CharEntry("暴雷", listOf("暴雷", "Fuse"))
    )),
    SourceGroup("Valorant", listOf("Valorant", "瓦罗兰特", "无畏契约", "VAL"), listOf(
        CharEntry("捷风", listOf("捷风", "Jett")),
        CharEntry("贤者", listOf("贤者", "Sage")),
        CharEntry("蝰蛇", listOf("蝰蛇", "Viper")),
        CharEntry("蕾娜", listOf("蕾娜", "Reyna")),
        CharEntry("奇乐", listOf("奇乐", "Killjoy")),
        CharEntry("雷兹", listOf("雷兹", "Raze")),
        CharEntry("星礈", listOf("星礈", "Astra")),
        CharEntry("斯凯", listOf("斯凯", "Skye")),
        CharEntry("霓虹", listOf("霓虹", "Neon")),
        CharEntry("黑梦", listOf("黑梦", "Fade")),
        CharEntry("死锁", listOf("死锁", "Deadlock")),
        CharEntry("珂乐芙", listOf("珂乐芙", "Clove"))
    )),
    SourceGroup("街头霸王", listOf("街头霸王", "街霸6", "街霸", "Street Fighter 6", "Street Fighter", "SF6", "SF"), listOf(
        CharEntry("春丽", listOf("春丽", "Chun Li", "春丽")),
        CharEntry("卡米", listOf("卡米", "Cammy")),
        CharEntry("朱莉", listOf("朱莉", "Juri", "韩蛛俐")),
        CharEntry("劳拉", listOf("劳拉", "Laura")),
        CharEntry("神月卡琳", listOf("神月卡琳", "Karin")),
        CharEntry("伊吹", listOf("伊吹", "Ibuki")),
        CharEntry("真琴", listOf("真琴", "Makoto")),
        CharEntry("樱", listOf("樱", "Sakura")),
        CharEntry("萝丝", listOf("萝丝", "Rose")),
        CharEntry("梅纳特", listOf("梅纳特", "Menat")),
        CharEntry("毒药", listOf("毒药", "Poison")),
        CharEntry("艾莲娜", listOf("艾莲娜", "Elena")),
        CharEntry("C Viper", listOf("C Viper", "Viper")),
        CharEntry("不知火舞", listOf("不知火舞", "Mai Shiranui", "舞", "Mai"))
    )),
    SourceGroup("拳皇", listOf("拳皇", "King of Fighters", "KOF"), listOf(
        CharEntry("不知火舞", listOf("不知火舞", "Mai Shiranui", "舞", "Mai")),
        CharEntry("坂崎百合", listOf("坂崎百合", "Yuri Sakazaki", "百合")),
        CharEntry("雅典娜", listOf("雅典娜", "Athena Asamiya", "麻宫雅典娜")),
        CharEntry("莉安娜", listOf("莉安娜", "Leona Heidern")),
        CharEntry("库拉", listOf("库拉", "Kula Diamond")),
        CharEntry("安琪儿", listOf("安琪儿", "Angel")),
        CharEntry("布鲁玛丽", listOf("布鲁玛丽", "Blue Mary", "玛丽")),
        CharEntry("凡妮莎", listOf("凡妮莎", "Vanessa")),
        CharEntry("鞭", listOf("鞭", "Whip")),
        CharEntry("神乐千鹤", listOf("神乐千鹤", "Chizuru Kagura")),
        CharEntry("夏尔美", listOf("夏尔美", "Shermie")),
        CharEntry("麦卓", listOf("麦卓", "Mature")),
        CharEntry("薇思", listOf("薇思", "Vice"))
    )),
    SourceGroup("死或生", listOf("死或生", "生或死", "生或死5", "Dead or Alive 5", "Dead or Alive", "DOA5", "DOA"), listOf(
        CharEntry("霞", listOf("霞", "Kasumi")),
        CharEntry("绫音", listOf("绫音", "Ayane")),
        CharEntry("瞳", listOf("瞳", "Hitomi")),
        CharEntry("雷芳", listOf("雷芳", "Lei Fang")),
        CharEntry("蒂娜", listOf("蒂娜", "Tina")),
        CharEntry("海莲娜", listOf("海莲娜", "Helena")),
        CharEntry("克里斯蒂", listOf("克里斯蒂", "Christie")),
        CharEntry("红叶", listOf("红叶", "Momiji")),
        CharEntry("瑞秋", listOf("瑞秋", "Rachel")),
        CharEntry("穗乃果", listOf("穗乃果", "Honoka")),
        CharEntry("玛丽萝丝", listOf("玛丽萝丝", "Marie Rose")),
        CharEntry("女天狗", listOf("女天狗", "Nyotengu")),
        CharEntry("Phase4", listOf("Phase4", "Phase 4")),
        CharEntry("美咲", listOf("美咲", "Misaki")),
        CharEntry("露娜", listOf("露娜", "Luna")),
        CharEntry("环", listOf("环", "Tamaki")),
        CharEntry("雪乃", listOf("雪乃", "Yukino")),
        CharEntry("菲欧娜", listOf("菲欧娜", "Fiona")),
        CharEntry("凪", listOf("凪", "Nagisa")),
        CharEntry("小百合", listOf("小百合", "Sayuri")),
        CharEntry("帕蒂", listOf("帕蒂", "Patty")),
        CharEntry("莫妮卡", listOf("莫妮卡", "Monica")),
        CharEntry("洛贝利亚", listOf("洛贝利亚", "Lobelia")),
        CharEntry("奈奈美", listOf("奈奈美", "Nanami")),
        CharEntry("艾莉丝", listOf("艾莉丝", "Elise")),
        CharEntry("艾米", listOf("艾米", "Amy")),
        CharEntry("香迪", listOf("香迪", "Shandy")),
        CharEntry("小春", listOf("小春", "Koharu")),
        CharEntry("蒂娜", listOf("蒂娜", "Tina"))
    )),
    SourceGroup("死或生 沙滩排球", listOf("死或生 沙滩排球", "DOAX", "DOAXVV"), listOf(
        CharEntry("霞", listOf("霞", "Kasumi")),
        CharEntry("绫音", listOf("绫音", "Ayane")),
        CharEntry("瞳", listOf("瞳", "Hitomi")),
        CharEntry("玛丽萝丝", listOf("玛丽萝丝", "Marie Rose")),
        CharEntry("穗乃果", listOf("穗乃果", "Honoka")),
        CharEntry("女天狗", listOf("女天狗", "Nyotengu"))
    )),
    SourceGroup("灵魂能力", listOf("灵魂能力", "Soul Calibur", "SC"), listOf(
        CharEntry("索菲蒂亚", listOf("索菲蒂亚", "Sophitia")),
        CharEntry("艾薇", listOf("艾薇", "Ivy", "伊莎贝拉")),
        CharEntry("多喜", listOf("多喜", "Taki")),
        CharEntry("成美那", listOf("成美那", "Seong Mi Na")),
        CharEntry("卡珊德拉", listOf("卡珊德拉", "Cassandra")),
        CharEntry("雪华", listOf("雪华", "Setsuka")),
        CharEntry("提拉", listOf("提拉", "Tira")),
        CharEntry("希尔德", listOf("希尔德", "Hilde")),
        CharEntry("艾米", listOf("艾米", "Amy")),
        CharEntry("薇奥拉", listOf("薇奥拉", "Viola")),
        CharEntry("蕾夏", listOf("蕾夏", "Leixia")),
        CharEntry("凪", listOf("凪", "Natsu"))
    )),
    SourceGroup("真人快打", listOf("真人快打", "Mortal Kombat", "MK"), listOf(
        CharEntry("索妮娅", listOf("索妮娅", "Sonya", "Sonya Blade")),
        CharEntry("吉塔娜", listOf("吉塔娜", "Kitana")),
        CharEntry("米莉娜", listOf("米莉娜", "Mileena")),
        CharEntry("翡翠", listOf("翡翠", "Jade")),
        CharEntry("辛黛尔", listOf("辛黛尔", "Sindel")),
        CharEntry("斯卡蕾特", listOf("斯卡蕾特", "Skarlet")),
        CharEntry("卡西凯奇", listOf("卡西凯奇", "Cassie Cage")),
        CharEntry("弗萝", listOf("弗萝", "Frost")),
        CharEntry("阿什拉", listOf("阿什拉", "Ashrah")),
        CharEntry("李梅", listOf("李梅", "Li Mei")),
        CharEntry("塔尼亚", listOf("塔尼亚", "Tanya")),
        CharEntry("妮塔拉", listOf("妮塔拉", "Nitara")),
        CharEntry("希瓦", listOf("希瓦", "Sheeva"))
    )),
    SourceGroup("猎天使魔女", listOf("猎天使魔女", "Bayonetta", "蓓优妮塔"), listOf(
        CharEntry("贝优妮塔", listOf("贝优妮塔", "Bayonetta", "贝姐", "Cereza")),
        CharEntry("贞德", listOf("贞德", "Jeanne")),
        CharEntry("罗莎", listOf("罗莎", "Rosa")),
        CharEntry("薇奥拉", listOf("薇奥拉", "Viola"))
    )),
    SourceGroup("鬼泣", listOf("鬼泣5", "鬼泣", "Devil May Cry 5", "Devil May Cry", "DMC"), listOf(
        CharEntry("翠西", listOf("翠西", "Trish")),
        CharEntry("蕾蒂", listOf("蕾蒂", "Lady", "玛丽")),
        CharEntry("妮可", listOf("妮可", "Nico")),
        CharEntry("露西亚", listOf("露西亚", "Lucia")),
        CharEntry("凯特", listOf("凯特", "Kat"))
    )),
    SourceGroup("女神异闻录", listOf("女神异闻录5", "女神异闻录 5", "女神异闻录3", "女神异闻录4", "女神异闻录", "Persona 5", "Persona 4", "Persona 3", "Persona", "P5", "P4", "P3"), listOf(
        CharEntry("高卷杏", listOf("高卷杏", "杏", "Ann", "Panther")),
        CharEntry("新岛真", listOf("新岛真", "真", "Makoto", "Queen")),
        CharEntry("佐仓双叶", listOf("佐仓双叶", "双叶", "Futaba", "Navi")),
        CharEntry("奥村春", listOf("奥村春", "春", "Haru", "Noir")),
        CharEntry("芳泽霞", listOf("芳泽霞", "霞", "Kasumi", "Violet")),
        CharEntry("拉雯妲", listOf("拉雯妲", "Lavenza")),
        CharEntry("卡萝莉娜", listOf("卡萝莉娜", "Caroline")),
        CharEntry("贾斯蒂丝", listOf("贾斯蒂丝", "Justine")),
        CharEntry("新岛冴", listOf("新岛冴", "Sae")),
        CharEntry("武见妙", listOf("武见妙", "Tae", "死神医生")),
        CharEntry("一色若叶", listOf("一色若叶", "Ichiko")),
        CharEntry("久须美", listOf("久须美", "Hifumi")),
        CharEntry("千早", listOf("千早", "Chihaya")),
        CharEntry("川上", listOf("川上", "Sadayo")),
        CharEntry("花村阳子", listOf("花村阳子", "Chie", "P4")),
        CharEntry("里中千枝", listOf("里中千枝", "Chie Satonaka")),
        CharEntry("天城雪子", listOf("天城雪子", "Yukiko")),
        CharEntry("巽完二", listOf("巽完二", "Rise", "理世")),
        CharEntry("白钟直斗", listOf("白钟直斗", "Naoto")),
        CharEntry("玛丽", listOf("玛丽", "Marie")),
        CharEntry("桐条美鹤", listOf("桐条美鹤", "Mitsuru")),
        CharEntry("岳羽由加莉", listOf("岳羽由加莉", "Yukari")),
        CharEntry("山岸风花", listOf("山岸风花", "Fuuka")),
        CharEntry("埃癸斯", listOf("埃癸斯", "Aigis", "艾吉斯")),
        CharEntry("伊丽莎白", listOf("伊丽莎白", "Elizabeth"))
    )),
    SourceGroup("塞尔达传说", listOf("塞尔达传说 王国之泪", "塞尔达传说 旷野之息", "塞尔达传说", "塞尔达", "Zelda", "Breath of the Wild", "BOTW", "TOTK"), listOf(
        CharEntry("塞尔达", listOf("塞尔达", "Zelda", "公主")),
        CharEntry("英帕", listOf("英帕", "Impa")),
        CharEntry("米法", listOf("米法", "Mipha")),
        CharEntry("乌尔波扎", listOf("乌尔波扎", "Urbosa")),
        CharEntry("露珠", listOf("露珠", "Riju")),
        CharEntry("帕雅", listOf("帕雅", "Paya")),
        CharEntry("普尔亚", listOf("普尔亚", "Purah")),
        CharEntry("中庭", listOf("中庭", "Midna")),
        CharEntry("泰特拉", listOf("泰特拉", "Tetra")),
        CharEntry("希克", listOf("希克", "Sheik"))
    )),
    SourceGroup("火焰纹章", listOf("火焰纹章", "Fire Emblem", "FE"), listOf(
        CharEntry("贝雷特", listOf("贝雷特", "Byleth", "老师")),
        CharEntry("艾黛尔贾特", listOf("艾黛尔贾特", "Edelgard", "皇女")),
        CharEntry("露米娜", listOf("露米娜", "Lucina")),
        CharEntry("卡米拉", listOf("卡米拉", "Camilla")),
        CharEntry("亚莎", listOf("亚莎", "Azura")),
        CharEntry("神威", listOf("神威", "Corrin")),
        CharEntry("赛莉卡", listOf("赛莉卡", "Celica")),
        CharEntry("琳", listOf("琳", "Lyn")),
        CharEntry("蒂亚莫", listOf("蒂亚莫", "Tharja")),
        CharEntry("索提斯", listOf("索提斯", "Sothis")),
        CharEntry("蕾雅", listOf("蕾雅", "Rhea")),
        CharEntry("多萝西娅", listOf("多萝西娅", "Dorothea")),
        CharEntry("英谷莉特", listOf("英谷莉特", "Ingrid")),
        CharEntry("贝尔娜提塔", listOf("贝尔娜提塔", "Bernadetta")),
        CharEntry("佩托拉", listOf("佩托拉", "Petra")),
        CharEntry("梅尔赛德丝", listOf("梅尔赛德丝", "Mercedes")),
        CharEntry("莉丝缇亚", listOf("莉丝缇亚", "Lysithea")),
        CharEntry("玛丽安", listOf("玛丽安", "Marianne")),
        CharEntry("希尔妲", listOf("希尔妲", "Hilda")),
        CharEntry("雷欧妮", listOf("雷欧妮", "Leonie")),
        CharEntry("萨米亚", listOf("萨米亚", "Shamir"))
    )),
    SourceGroup("异度神剑", listOf("异度神剑3", "异度神剑2", "异度神剑", "Xenoblade", "XB2", "XB3"), listOf(
        CharEntry("焰", listOf("焰", "Pyra", "_homura")),
        CharEntry("光", listOf("光", "Mythra", "hikari")),
        CharEntry("尼亚", listOf("尼亚", "Nia")),
        CharEntry("花", listOf("花", "Poppi")),
        CharEntry("菲奥伦", listOf("菲奥伦", "Fiora")),
        CharEntry("梅莉亚", listOf("梅莉亚", "Melia")),
        CharEntry("莎尔拉特", listOf("莎尔拉特", "Sharla")),
        CharEntry("布里吉德", listOf("布里吉德", "Brighid")),
        CharEntry("潘多利亚", listOf("潘多利亚", "Pandoria")),
        CharEntry("梅蕾芙", listOf("梅蕾芙", "Morag")),
        CharEntry("萝拉", listOf("萝拉", "Lora")),
        CharEntry("米奥", listOf("米奥", "Mio")),
        CharEntry("安洁", listOf("安洁", "Eunie")),
        CharEntry("圣奈", listOf("圣奈", "Sena"))
    )),
    SourceGroup("宝可梦", listOf("宝可梦", "精灵宝可梦", "Pokemon", "口袋妖怪", "神奇宝贝"), listOf(
        CharEntry("竹兰", listOf("竹兰", "Cynthia", "希罗娜")),
        CharEntry("小光", listOf("小光", "Dawn", "光")),
        CharEntry("小遥", listOf("小遥", "May")),
        CharEntry("莎莉娜", listOf("莎莉娜", "Serena")),
        CharEntry("莉莉艾", listOf("莉莉艾", "Lillie")),
        CharEntry("玛奥", listOf("玛奥", "Marnie")),
        CharEntry("格洛丽亚", listOf("格洛丽亚", "Gloria")),
        CharEntry("妮莫", listOf("妮莫", "Nemona")),
        CharEntry("莉科", listOf("莉科", "Liko")),
        CharEntry("内莎", listOf("内莎", "Nessa")),
        CharEntry("比音", listOf("比音", "Bea")),
        CharEntry("卡瑚", listOf("卡瑚", "Korrina")),
        CharEntry("希特隆", listOf("希特隆", "Clemont")),
        CharEntry("露莎米涅", listOf("露莎米涅", "Lusamine")),
        CharEntry("茜紫拉", listOf("茜紫拉", "Zinnia")),
        CharEntry("莉莉丝", listOf("莉莉丝", "Lisia"))
    )),
    SourceGroup("密特罗德", listOf("密特罗德", "Metroid", "银河战士"), listOf(
        CharEntry("萨姆斯", listOf("萨姆斯", "Samus", "萨姆斯阿兰"))
    )),
    SourceGroup("魔兽世界", listOf("魔兽世界", "World of Warcraft", "WoW"), listOf(
        CharEntry("吉安娜", listOf("吉安娜", "Jaina", "吉安娜普罗德摩尔")),
        CharEntry("希尔瓦娜斯", listOf("希尔瓦娜斯", "Sylvanas", "女妖之王")),
        CharEntry("泰兰德", listOf("泰兰德", "Tyrande", "月之女祭司")),
        CharEntry("亚历山德拉萨斯", listOf("亚历山德拉萨斯", "Alexstrasza", "红龙女王")),
        CharEntry("艾萨拉", listOf("艾萨拉", "Azshara")),
        CharEntry("瓦莉拉", listOf("瓦莉拉", "Valeera")),
        CharEntry("莉亚德琳", listOf("莉亚德琳", "Liadrin")),
        CharEntry("玛维", listOf("玛维", "Maiev", "守望者")),
        CharEntry("维蕾萨", listOf("维蕾萨", "Vereesa")),
        CharEntry("瓦丝琪", listOf("瓦丝琪", "Vashj")),
        CharEntry("奥妮克希亚", listOf("奥妮克希亚", "Onyxia")),
        CharEntry("凡妮莎", listOf("凡妮莎", "Vanessa")),
        CharEntry("加罗娜", listOf("加罗娜", "Garona"))
    )),
    SourceGroup("星际争霸", listOf("星际争霸", "StarCraft", "SC"), listOf(
        CharEntry("凯瑞甘", listOf("凯瑞甘", "Kerrigan", "刀锋女王")),
        CharEntry("诺娃", listOf("诺娃", "Nova")),
        CharEntry("莎拉", listOf("莎拉", "Sarah"))
    )),
    SourceGroup("暗黑破坏神", listOf("暗黑破坏神4", "暗黑破坏神3", "暗黑破坏神", "Diablo 4", "Diablo 3", "Diablo", "D4", "D3"), listOf(
        CharEntry("莉莉丝", listOf("莉莉丝", "Lilith", "暗黑之母")),
        CharEntry("伊雷娜", listOf("伊雷娜", "Eirena", "魔女")),
        CharEntry("艾希拉", listOf("艾希拉", "Ashera"))
    )),
    SourceGroup("质量效应", listOf("质量效应", "Mass Effect", "ME"), listOf(
        CharEntry("莉亚拉", listOf("莉亚拉", "Liara")),
        CharEntry("塔莉", listOf("塔莉", "Tali")),
        CharEntry("阿什丽", listOf("阿什丽", "Ashley")),
        CharEntry("米兰达", listOf("米兰达", "Miranda")),
        CharEntry("杰克", listOf("杰克", "Jack")),
        CharEntry("萨玛拉", listOf("萨玛拉", "Samara")),
        CharEntry("霞", listOf("霞", "Kasumi")),
        CharEntry("EDI", listOf("EDI")),
        CharEntry("皮比", listOf("皮比", "Peebee")),
        CharEntry("科拉", listOf("科拉", "Cora")),
        CharEntry("维特拉", listOf("维特拉", "Vetra"))
    )),
    SourceGroup("龙腾世纪", listOf("龙腾世纪", "Dragon Age", "DA"), listOf(
        CharEntry("莫瑞甘", listOf("莫瑞甘", "Morrigan")),
        CharEntry("蕾莉安娜", listOf("蕾莉安娜", "Leliana")),
        CharEntry("卡珊德拉", listOf("卡珊德拉", "Cassandra")),
        CharEntry("塞拉", listOf("塞拉", "Sera")),
        CharEntry("约瑟芬", listOf("约瑟芬", "Josephine")),
        CharEntry("薇薇安", listOf("薇薇安", "Vivienne")),
        CharEntry("梅丽尔", listOf("梅丽尔", "Merrill")),
        CharEntry("伊莎贝拉", listOf("伊莎贝拉", "Isabela"))
    )),
    SourceGroup("刺客信条", listOf("刺客信条", "Assassins Creed", "AC"), listOf(
        CharEntry("艾芙琳", listOf("艾芙琳", "Aveline")),
        CharEntry("艾莉丝", listOf("艾莉丝", "Elise")),
        CharEntry("伊薇", listOf("伊薇", "Evie")),
        CharEntry("卡珊德拉", listOf("卡珊德拉", "Kassandra")),
        CharEntry("艾雅", listOf("艾雅", "Aya", "阿蒙内特")),
        CharEntry("艾沃尔", listOf("艾沃尔", "Eivor")),
        CharEntry("蕾拉", listOf("蕾拉", "Layla"))
    )),
    SourceGroup("GTA", listOf("GTA5", "GTA6", "GTA", "Grand Theft Auto"), listOf(
        CharEntry("崔西", listOf("崔西", "Tracey")),
        CharEntry("米歇尔", listOf("米歇尔", "Michelle"))
    )),
    SourceGroup("荒野大镖客", listOf("荒野大镖客2", "荒野大镖客", "Red Dead Redemption", "RDR2", "RDR"), listOf(
        CharEntry("赛迪", listOf("赛迪", "Sadie")),
        CharEntry("阿比盖尔", listOf("阿比盖尔", "Abigail")),
        CharEntry("邦妮", listOf("邦妮", "Bonnie"))
    )),
    SourceGroup("战神", listOf("战神", "战神 诸神黄昏", "God of War", "God of War Ragnarok"), listOf(
        CharEntry("芙蕾雅", listOf("芙蕾雅", "Freya")),
        CharEntry("丝露德", listOf("丝露德", "Thrud")),
        CharEntry("菲", listOf("菲", "Faye")),
        CharEntry("安格尔伯达", listOf("安格尔伯达", "Angrboda"))
    )),
    SourceGroup("地平线", listOf("地平线 西之绝境", "地平线 零之曙光", "地平线", "Horizon Forbidden West", "Horizon Zero Dawn", "Horizon"), listOf(
        CharEntry("埃洛伊", listOf("埃洛伊", "Aloy")),
        CharEntry("塔拉娜", listOf("塔拉娜", "Talanah")),
        CharEntry("索娜", listOf("索娜", "Sona"))
    )),
    SourceGroup("死亡搁浅", listOf("死亡搁浅", "Death Stranding"), listOf(
        CharEntry("芙拉吉尔", listOf("芙拉吉尔", "Fragile")),
        CharEntry("玛玛", listOf("玛玛", "Mama")),
        CharEntry("洛克妮", listOf("洛克妮", "Lockne")),
        CharEntry("亚美莉", listOf("亚美莉", "Amelie"))
    )),
    SourceGroup("只狼", listOf("只狼", "只狼 影逝二度", "Sekiro"), listOf(
        CharEntry("永真", listOf("永真", "Emma")),
        CharEntry("九郎", listOf("九郎", "Kuro"))
    )),
    SourceGroup("对马岛之魂", listOf("对马岛之魂", "对马岛", "Ghost of Tsushima"), listOf(
        CharEntry("结奈", listOf("结奈", "Yuna")),
        CharEntry("政子", listOf("政子", "Masako"))
    )),
    SourceGroup("尼尔 人工生命", listOf("尼尔 人工生命", "尼尔人工生命", "NieR Replicant"), listOf(
        CharEntry("凯妮", listOf("凯妮", "Kaine")),
        CharEntry("艾米尔", listOf("艾米尔", "Emil"))
    )),
    SourceGroup("超次元游戏 海王星", listOf("超次元游戏 海王星", "海王星", "Neptunia"), listOf(
        CharEntry("涅普缇努", listOf("涅普缇努", "Neptune", "涅普", "紫色之心")),
        CharEntry("涅普姬雅", listOf("涅普姬雅", "Nepgear", "紫色妹妹")),
        CharEntry("诺瓦露", listOf("诺瓦露", "Noire", "黑色之心")),
        CharEntry("布兰", listOf("布兰", "Blanc", "白色之心")),
        CharEntry("贝露", listOf("贝露", "Vert", "绿色之心")),
        CharEntry("普露露特", listOf("普露露特", "Plutia", "澪色之心")),
        CharEntry("优妮", listOf("优妮", "Uni", "黑色妹妹")),
        CharEntry("萝姆", listOf("萝姆", "Rom", "白色妹妹")),
        CharEntry("拉姆", listOf("拉姆", "Ram", "白色妹妹")),
        CharEntry("空", listOf("空", "Uzume", "澄色之心")),
        CharEntry("康帕", listOf("康帕", "Compa")),
        CharEntry("IF", listOf("IF", "爱耶芙"))
    )),
    SourceGroup("闪乱神乐", listOf("闪乱神乐", "Senran Kagura"), listOf(
        CharEntry("飞鸟", listOf("飞鸟", "Asuka")),
        CharEntry("焰", listOf("焰", "Homura")),
        CharEntry("雪泉", listOf("雪泉", "Yumi")),
        CharEntry("雅绯", listOf("雅绯", "Miyabi")),
        CharEntry("斑鸠", listOf("斑鸠", "Ikaruga")),
        CharEntry("葛城", listOf("葛城", "Katsuragi")),
        CharEntry("柳生", listOf("柳生", "Yagyuu")),
        CharEntry("云雀", listOf("云雀", "Hibari")),
        CharEntry("未来", listOf("未来", "Mirai")),
        CharEntry("春花", listOf("春花", "Haruka")),
        CharEntry("日影", listOf("日影", "Hikage")),
        CharEntry("咏", listOf("咏", "Yozakura")),
        CharEntry("紫", listOf("紫", "Murasaki")),
        CharEntry("两姬", listOf("两姬", "Ryouna")),
        CharEntry("两备", listOf("两备", "Ryoubi")),
        CharEntry("神乐", listOf("神乐", "Murakumo")),
        CharEntry("四季", listOf("四季", "Shiki")),
        CharEntry("莲华", listOf("莲华", "Renka")),
        CharEntry("烟花", listOf("烟花", "Hanabi")),
        CharEntry("河童", listOf("河童", "Kafuru")),
        CharEntry("大道寺", listOf("大道寺", "Daidouji")),
        CharEntry("铃音", listOf("铃音", "Rin")),
        CharEntry("雪不归", listOf("雪不归", "Sayuri"))
    )),
    SourceGroup("新世纪福音战士", listOf("新世纪福音战士", "福音战士", "EVA", "Evangelion"), listOf(
        CharEntry("绫波丽", listOf("绫波丽", "Rei", "丽", "绫波零")),
        CharEntry("明日香", listOf("明日香", "Asuka", "式波")),
        CharEntry("葛城美里", listOf("葛城美里", "Misato", "美里")),
        CharEntry("赤木律子", listOf("赤木律子", "Ritsuko")),
        CharEntry("真希波", listOf("真希波", "Mari")),
        CharEntry("铃原樱", listOf("铃原樱", "Sakura")),
        CharEntry("伊吹玛雅", listOf("伊吹玛雅", "Maya"))
    )),
    SourceGroup("魔法少女小圆", listOf("魔法少女小圆", "Puella Magi Madoka Magica", "小圆"), listOf(
        CharEntry("鹿目圆", listOf("鹿目圆", "圆", "Madoka")),
        CharEntry("晓美焰", listOf("晓美焰", "焰", "Homura", "吼姆拉")),
        CharEntry("巴麻美", listOf("巴麻美", "麻美", "Mami", "学姐")),
        CharEntry("美树沙耶香", listOf("美树沙耶香", "沙耶香", "Sayaka")),
        CharEntry("佐仓杏子", listOf("佐仓杏子", "杏子", "Kyoko")),
        CharEntry("百江渚", listOf("百江渚", "渚", "Nagisa"))
    )),
    SourceGroup("鬼灭之刃", listOf("鬼灭之刃", "Demon Slayer", "Kimetsu no Yaiba"), listOf(
        CharEntry("灶门祢豆子", listOf("祢豆子", "Nezuko", "豆子")),
        CharEntry("蝴蝶忍", listOf("蝴蝶忍", "忍", "Shinobu")),
        CharEntry("甘露寺蜜璃", listOf("甘露寺蜜璃", "蜜璃", "Mitsuri", "恋柱")),
        CharEntry("栗花落香奈乎", listOf("香奈乎", "Kanao")),
        CharEntry("珠世", listOf("珠世", "Tamayo")),
        CharEntry("堕姬", listOf("堕姬", "Daki")),
        CharEntry("胡蝶香奈惠", listOf("香奈惠", "Kanae")),
        CharEntry("真妃", listOf("真妃", "Makomo")),
        CharEntry("雏鹤", listOf("雏鹤", "Hinatsuru")),
        CharEntry("牧绪", listOf("牧绪", "Makio")),
        CharEntry("须磨", listOf("须磨", "Suma"))
    )),
    SourceGroup("咒术回战", listOf("咒术回战", "Jujutsu Kaisen", "JJK"), listOf(
        CharEntry("钉崎野蔷薇", listOf("钉崎", "野蔷薇", "Nobara")),
        CharEntry("禅院真希", listOf("真希", "Maki")),
        CharEntry("冥冥", listOf("冥冥", "Mei Mei")),
        CharEntry("家入硝子", listOf("硝子", "Shoko")),
        CharEntry("庵歌姬", listOf("歌姬", "Utahime")),
        CharEntry("三轮霞", listOf("三轮", "Miwa")),
        CharEntry("理子", listOf("理子", "Riko"))
    )),
    SourceGroup("电锯人", listOf("电锯人", "Chainsaw Man", "CSM"), listOf(
        CharEntry("玛奇玛", listOf("玛奇玛", "Makima", "支配恶魔")),
        CharEntry("帕瓦", listOf("帕瓦", "Power", "血之魔人")),
        CharEntry("姬野", listOf("姬野", "Himeno")),
        CharEntry("小夜子", listOf("小夜子", "Kobeni")),
        CharEntry("蕾塞", listOf("蕾塞", "Reze")),
        CharEntry("光希", listOf("光希", "Quanxi")),
        CharEntry("三鹰朝", listOf("三鹰朝", "Asa")),
        CharEntry("战争恶魔", listOf("战争恶魔", "Yoru")),
        CharEntry("那由多", listOf("那由多", "Nayuta"))
    )),
    SourceGroup("间谍过家家", listOf("间谍过家家", "Spy x Family"), listOf(
        CharEntry("约尔", listOf("约尔", "Yor", "杀手太太")),
        CharEntry("阿尼亚", listOf("阿尼亚", "Anya")),
        CharEntry("菲奥娜", listOf("菲奥娜", "Fiona")),
        CharEntry("贝琪", listOf("贝琪", "Becky"))
    )),
    SourceGroup("刀剑神域", listOf("刀剑神域", "Sword Art Online", "SAO"), listOf(
        CharEntry("亚丝娜", listOf("亚丝娜", "Asuna", "闪光")),
        CharEntry("莉法", listOf("莉法", "Leafa", "直叶")),
        CharEntry("诗乃", listOf("诗乃", "Sinon", "朝田诗乃")),
        CharEntry("优纪", listOf("优纪", "Yuuki")),
        CharEntry("爱丽丝", listOf("爱丽丝", "Alice", "整合骑士")),
        CharEntry("葵妮拉", listOf("葵妮拉", "Quinella", "管理员")),
        CharEntry("利涅娜", listOf("利涅娜", "Liena")),
        CharEntry("索尔蒂蕾娜", listOf("索尔蒂蕾娜", "Sortiliena"))
    )),
    SourceGroup("进击的巨人", listOf("进击的巨人", "Attack on Titan", "AOT", "进击"), listOf(
        CharEntry("三笠", listOf("三笠", "Mikasa", "三笠阿克曼")),
        CharEntry("阿尼", listOf("阿尼", "Annie", "女型巨人")),
        CharEntry("希斯特莉亚", listOf("希斯特莉亚", "Historia", "克里斯塔")),
        CharEntry("莎夏", listOf("莎夏", "Sasha", "土豆女")),
        CharEntry("尤弥尔", listOf("尤弥尔", "Ymir")),
        CharEntry("韩吉", listOf("韩吉", "Hange")),
        CharEntry("皮克", listOf("皮克", "Pieck", "车力巨人")),
        CharEntry("贾碧", listOf("贾碧", "Gabi")),
        CharEntry("卡露拉", listOf("卡露拉", "Carla"))
    )),
    SourceGroup("火影忍者", listOf("火影忍者", "Naruto", "火影", "BORUTO"), listOf(
        CharEntry("日向雏田", listOf("雏田", "Hinata", "日向")),
        CharEntry("春野樱", listOf("小樱", "樱", "Sakura")),
        CharEntry("纲手", listOf("纲手", "Tsunade", "五代火影")),
        CharEntry("山中井野", listOf("井野", "Ino")),
        CharEntry("日向花火", listOf("花火", "Hanabi")),
        CharEntry("手鞠", listOf("手鞠", "Temari")),
        CharEntry("漩涡玖辛奈", listOf("玖辛奈", "Kushina")),
        CharEntry("小南", listOf("小南", "Konan")),
        CharEntry("照美冥", listOf("照美冥", "Mei")),
        CharEntry("夕日红", listOf("夕日红", "Kurenai")),
        CharEntry("萨达拉", listOf("萨达拉", "Sarada")),
        CharEntry("香磷", listOf("香磷", "Karin")),
        CharEntry("黑土", listOf("黑土", "Kurotsuchi"))
    )),
    SourceGroup("海贼王", listOf("海贼王", "One Piece", "航海王"), listOf(
        CharEntry("娜美", listOf("娜美", "Nami", "猫贼")),
        CharEntry("妮可罗宾", listOf("罗宾", "Robin", "妮可罗宾")),
        CharEntry("波雅汉库克", listOf("汉库克", "Boa Hancock", "女帝")),
        CharEntry("薇薇", listOf("薇薇", "Vivi", "奈菲鲁塔丽")),
        CharEntry("白星", listOf("白星", "Shirahoshi")),
        CharEntry("佩罗娜", listOf("佩罗娜", "Perona")),
        CharEntry("达斯琪", listOf("达斯琪", "Tashigi")),
        CharEntry("大和", listOf("大和", "Yamato")),
        CharEntry("加洛特", listOf("加洛特", "Carrot")),
        CharEntry("卡莉法", listOf("卡莉法", "Kalifa")),
        CharEntry("凯米", listOf("凯米", "Camie")),
        CharEntry("蕾玖", listOf("蕾玖", "Reiju")),
        CharEntry("布丁", listOf("布丁", "Pudding"))
    )),
    SourceGroup("龙珠", listOf("龙珠", "Dragon Ball", "DB", "龙珠Z", "龙珠超"), listOf(
        CharEntry("布尔玛", listOf("布尔玛", "Bulma")),
        CharEntry("人造人18号", listOf("人造人18号", "18号", "Android 18")),
        CharEntry("比迪丽", listOf("比迪丽", "Videl")),
        CharEntry("琪琪", listOf("琪琪", "Chi Chi")),
        CharEntry("兰琪", listOf("兰琪", "Launch")),
        CharEntry("小芳", listOf("小芳", "Pan")),
        CharEntry("开尔弗拉", listOf("开尔弗拉", "Caulifla")),
        CharEntry("卡莉芙拉", listOf("卡莉芙拉", "Kale")),
        CharEntry("凯芙拉", listOf("凯芙拉", "Kefla")),
        CharEntry("托娃", listOf("托娃", "Towa")),
        CharEntry("人造人21号", listOf("人造人21号", "21号", "Android 21"))
    )),
    SourceGroup("死神", listOf("死神", "Bleach"), listOf(
        CharEntry("朽木露琪亚", listOf("露琪亚", "Rukia")),
        CharEntry("井上织姬", listOf("织姬", "Orihime")),
        CharEntry("四枫院夜一", listOf("夜一", "Yoruichi")),
        CharEntry("松本乱菊", listOf("乱菊", "Rangiku")),
        CharEntry("碎蜂", listOf("碎蜂", "Soi Fon")),
        CharEntry("雏森桃", listOf("雏森桃", "Hinamori")),
        CharEntry("蒂雅赫丽贝尔", listOf("赫丽贝尔", "Halibel", "Tier")),
        CharEntry("涅莉艾露", listOf("涅莉艾露", "Nel")),
        CharEntry("卯之花烈", listOf("卯之花", "Unohana")),
        CharEntry("伊势七绪", listOf("七绪", "Nanao")),
        CharEntry("平子真子", listOf("平子", "Lisa")),
        CharEntry("日世里", listOf("日世里", "Hiyori")),
        CharEntry("白哉", listOf("白哉", "Mashiro")),
        CharEntry("志波空鹤", listOf("空鹤", "Kukaku")),
        CharEntry("黑崎夏梨", listOf("夏梨", "Tatsuki"))
    )),
    SourceGroup("JOJO的奇妙冒险", listOf("JOJO的奇妙冒险", "JOJO"), listOf(
        CharEntry("徐伦", listOf("徐伦", "Jolyne")),
        CharEntry("丽莎丽莎", listOf("丽莎丽莎", "Lisa Lisa")),
        CharEntry("特莉休", listOf("特莉休", "Trish")),
        CharEntry("康一", listOf("康一", "Yukako")),
        CharEntry("玛丽亚", listOf("玛丽亚", "Mariah"))
    )),
    SourceGroup("我的英雄学院", listOf("我的英雄学院", "My Hero Academia", "MHA", "小英雄"), listOf(
        CharEntry("丽日御茶子", listOf("丽日", "御茶子", "Uraraka", "茶子")),
        CharEntry("蛙吹梅雨", listOf("蛙吹", "梅雨", "Tsuyu", "青蛙")),
        CharEntry("八百万百", listOf("八百万", "百", "Momo", "创造")),
        CharEntry("耳郎响香", listOf("耳郎", "响香", "Jiro")),
        CharEntry("芦户三奈", listOf("芦户", "三奈", "Ashido")),
        CharEntry("叶隐透", listOf("叶隐", "透", "Hagakure")),
        CharEntry("渡我身子", listOf("渡我", "身子", "Toga", "托加")),
        CharEntry("午夜", listOf("午夜", "Midnight", "布雷萨米")),
        CharEntry("密丽欧", listOf("密丽欧", "Mirko", "米尔科"))
    )),
    SourceGroup("七大罪", listOf("七大罪", "Seven Deadly Sins"), listOf(
        CharEntry("伊丽莎白", listOf("伊丽莎白", "Elizabeth")),
        CharEntry("黛安", listOf("黛安", "Diane")),
        CharEntry("梅林", listOf("梅林", "Merlin")),
        CharEntry("伊莲恩", listOf("伊莲恩", "Elaine")),
        CharEntry("吉拉", listOf("吉拉", "Guila")),
        CharEntry("杰莉科", listOf("杰莉科", "Jericho"))
    )),
    SourceGroup("妖精的尾巴", listOf("妖精的尾巴", "Fairy Tail"), listOf(
        CharEntry("露西", listOf("露西", "Lucy", "露西哈特菲利亚")),
        CharEntry("艾尔莎", listOf("艾尔莎", "Erza", "艾尔莎舒卡勒托", "Titania")),
        CharEntry("朱毕安", listOf("朱毕安", "Juvia")),
        CharEntry("温蒂", listOf("温蒂", "Wendy")),
        CharEntry("米拉珍", listOf("米拉珍", "Mirajane")),
        CharEntry("蕾比", listOf("蕾比", "Levy")),
        CharEntry("卡娜", listOf("卡娜", "Cana")),
        CharEntry("梅维斯", listOf("梅维斯", "Mavis")),
        CharEntry("莉莎娜", listOf("莉莎娜", "Lisanna")),
        CharEntry("艾芭格琳", listOf("艾芭格琳", "Evergreen"))
    )),
    SourceGroup("一拳超人", listOf("一拳超人", "One Punch Man", "OPM"), listOf(
        CharEntry("吹雪", listOf("吹雪", "Fubuki", "地狱吹雪")),
        CharEntry("龙卷", listOf("龙卷", "Tatsumaki", "战栗的龙卷")),
        CharEntry("蚊女", listOf("蚊女", "Mosquito Girl")),
        CharEntry("水树", listOf("水树", "Mizuki")),
        CharEntry("急冻弹", listOf("急冻弹", "Do S")),
        CharEntry("翠子", listOf("翠子", "Suiko"))
    )),
    SourceGroup("Re Zero", listOf("Re Zero", "Re从零开始的异世界生活", "Re0"), listOf(
        CharEntry("艾米莉亚", listOf("艾米莉亚", "Emilia", "艾米")),
        CharEntry("雷姆", listOf("雷姆", "Rem")),
        CharEntry("拉姆", listOf("拉姆", "Ram")),
        CharEntry("碧翠丝", listOf("碧翠丝", "Beatrice", "贝阿")),
        CharEntry("库珥修", listOf("库珥修", "Crusch")),
        CharEntry("菲鲁特", listOf("菲鲁特", "Felt")),
        CharEntry("普莉希拉", listOf("普莉希拉", "Priscilla")),
        CharEntry("安娜塔西亚", listOf("安娜塔西亚", "Anastasia")),
        CharEntry("芙蕾德莉卡", listOf("芙蕾德莉卡", "Frederica")),
        CharEntry("佩特拉", listOf("佩特拉", "Petra")),
        CharEntry("艾姬多娜", listOf("艾姬多娜", "Echidna", "魔女"))
    )),
    SourceGroup("辉夜大小姐", listOf("辉夜大小姐", "辉夜姬想让人告白"), listOf(
        CharEntry("四宫辉夜", listOf("辉夜", "Kaguya", "四宫")),
        CharEntry("藤原千花", listOf("千花", "Chika", "藤原")),
        CharEntry("早坂爱", listOf("早坂", "Hayasaka"))
    )),
    SourceGroup("科学超电磁炮", listOf("科学超电磁炮", "A Certain Scientific Railgun", "超电磁炮", "御坂"), listOf(
        CharEntry("御坂美琴", listOf("御坂美琴", "美琴", "Misaka", "炮姐", "Bilibili")),
        CharEntry("白井黑子", listOf("白井黑子", "黑子", "Kuroko")),
        CharEntry("初春饰利", listOf("初春", "Uiharu")),
        CharEntry("佐天泪子", listOf("佐天", "Saten"))
    )),
    SourceGroup("魔法禁书目录", listOf("魔法禁书目录", "A Certain Magical Index", "禁书目录"), listOf(
        CharEntry("御坂美琴", listOf("御坂美琴", "美琴", "Misaka")),
        CharEntry("茵蒂克丝", listOf("茵蒂克丝", "Index")),
        CharEntry("白井黑子", listOf("白井黑子", "黑子", "Kuroko"))
    )),
    SourceGroup("王国之心", listOf("王国之心", "Kingdom Hearts", "KH"), listOf(
        CharEntry("凯莉", listOf("凯莉", "Kairi")),
        CharEntry("娜米妮", listOf("娜米妮", "Namine")),
        CharEntry("希恩", listOf("希恩", "Xion")),
        CharEntry("阿库娅", listOf("阿库娅", "Aqua")),
        CharEntry("拉尔克努", listOf("拉尔克努", "Larxene"))
    )),
    SourceGroup("勇者斗恶龙", listOf("勇者斗恶龙", "Dragon Quest", "DQ"), listOf(
        CharEntry("杰西卡", listOf("杰西卡", "Jessica")),
        CharEntry("比安卡", listOf("比安卡", "Bianca")),
        CharEntry("芙洛拉", listOf("芙洛拉", "Flora")),
        CharEntry("阿莉娜", listOf("阿莉娜", "Alena")),
        CharEntry("玛雅", listOf("玛雅", "Maya")),
        CharEntry("蜜娜", listOf("蜜娜", "Meena")),
        CharEntry("黛博拉", listOf("黛博拉", "Debora")),
        CharEntry("赛蕾娜", listOf("赛蕾娜", "Serena")),
        CharEntry("维罗妮卡", listOf("维罗妮卡", "Veronica")),
        CharEntry("玛尔蒂娜", listOf("玛尔蒂娜", "Martina")),
        CharEntry("洁德", listOf("洁德", "Jade"))
    )),
    SourceGroup("合金装备", listOf("合金装备", "Metal Gear Solid", "Metal Gear", "MGS"), listOf(
        CharEntry("梅丽尔", listOf("梅丽尔", "Meryl")),
        CharEntry("狙击狼", listOf("狙击狼", "Sniper Wolf")),
        CharEntry("艾娃", listOf("艾娃", "EVA")),
        CharEntry("The Boss", listOf("The Boss", "首领")),
        CharEntry("静静", listOf("静静", "Quiet")),
        CharEntry("帕兹", listOf("帕兹", "Paz")),
        CharEntry("奥尔加", listOf("奥尔加", "Olga")),
        CharEntry("幸运", listOf("幸运", "Fortune"))
    )),
    SourceGroup("星之海洋", listOf("星之海洋", "Star Ocean"), listOf(
        CharEntry("蕾娜", listOf("蕾娜", "Rena")),
        CharEntry("赛琳", listOf("赛琳", "Celine")),
        CharEntry("普蕾希斯", listOf("普蕾希斯", "Precis")),
        CharEntry("莉姆露", listOf("莉姆露", "Lymle")),
        CharEntry("缪莉亚", listOf("缪莉亚", "Myuria")),
        CharEntry("蕾咪", listOf("蕾咪", "Reimi")),
        CharEntry("莎拉", listOf("莎拉", "Sarah")),
        CharEntry("菲欧蕾", listOf("菲欧蕾", "Fiore"))
    )),
    SourceGroup("传说系列", listOf("传说系列", "Tales of", "TOZ", "TOB", "TOA"), listOf(
        CharEntry("柯蕾特", listOf("柯蕾特", "Colette")),
        CharEntry("藤林铃", listOf("藤林铃", "Sheena")),
        CharEntry("莉菲尔", listOf("莉菲尔", "Raine")),
        CharEntry("普蕾赛亚", listOf("普蕾赛亚", "Presea")),
        CharEntry("缇亚", listOf("缇亚", "Tear")),
        CharEntry("娜塔莉亚", listOf("娜塔莉亚", "Natalia")),
        CharEntry("安妮丝", listOf("安妮丝", "Anise")),
        CharEntry("茱蒂丝", listOf("茱蒂丝", "Judith")),
        CharEntry("莉塔", listOf("莉塔", "Rita")),
        CharEntry("艾丝缇莉洁", listOf("艾丝缇莉洁", "Estelle")),
        CharEntry("帕蒂", listOf("帕蒂", "Patty")),
        CharEntry("索菲", listOf("索菲", "Sophie")),
        CharEntry("雪莉亚", listOf("雪莉亚", "Cheria")),
        CharEntry("帕斯卡尔", listOf("帕斯卡尔", "Pascal")),
        CharEntry("米拉", listOf("米拉", "Milla")),
        CharEntry("蕾雅", listOf("蕾雅", "Leia")),
        CharEntry("艾莉洁", listOf("艾莉洁", "Elize")),
        CharEntry("萝丝", listOf("萝丝", "Rose")),
        CharEntry("艾莉莎", listOf("艾莉莎", "Alisha")),
        CharEntry("莱拉", listOf("莱拉", "Lailah")),
        CharEntry("艾德娜", listOf("艾德娜", "Edna")),
        CharEntry("玛吉露", listOf("玛吉露", "Magilou")),
        CharEntry("薇尔贝特", listOf("薇尔贝特", "Velvet")),
        CharEntry("艾蕾诺亚", listOf("艾蕾诺亚", "Eleanor")),
        CharEntry("琳薇儿", listOf("琳薇儿", "Rinwell")),
        CharEntry("希侬", listOf("希侬", "Shionne")),
        CharEntry("奇莎拉", listOf("奇莎拉", "Kisara"))
    )),
    SourceGroup("Fortnite", listOf("Fortnite", "堡垒之夜"), listOf(
        CharEntry("暗影", listOf("暗影", "Shadow")),
        CharEntry("中野", listOf("中野", "Raven")),
        CharEntry("艾思梅", listOf("艾思梅"))
    )),
    SourceGroup("PUBG", listOf("PUBG", "绝地求生"), listOf()),
    SourceGroup("CS2", listOf("CS2", "CSGO", "反恐精英", "Counter Strike"), listOf()),
    SourceGroup("星际战甲", listOf("星际战甲", "Warframe"), listOf(
        CharEntry("女武神", listOf("女武神", "Valkyr")),
        CharEntry("赛娃", listOf("赛娃", "Saryn")),
        CharEntry("小精灵", listOf("小精灵", "Wisp")),
        CharEntry("夜灵", listOf("夜灵", "Garuda")),
        CharEntry("弥桑", listOf("弥桑", "Mesa")),
        CharEntry("魅影", listOf("魅影", "Revenant")),
        CharEntry("翠玉", listOf("翠玉", "Jade"))
    )),
    SourceGroup("命运", listOf("命运2", "命运", "Destiny 2", "Destiny"), listOf(
        CharEntry("玛拉", listOf("玛拉", "Mara Sov")),
        CharEntry("艾可拉", listOf("艾可拉", "Ikora")),
        CharEntry("阿曼达", listOf("阿曼达", "Amanda")),
        CharEntry("艾瑞丝", listOf("艾瑞丝", "Eris"))
    )),
    SourceGroup("光环", listOf("光环", "Halo"), listOf(
        CharEntry("科塔娜", listOf("科塔娜", "Cortana"))
    )),
    SourceGroup("看门狗", listOf("看门狗", "Watch Dogs"), listOf(
        CharEntry("克拉拉", listOf("克拉拉", "Clara")),
        CharEntry("西塔拉", listOf("西塔拉", "Sitara"))
    )),
    SourceGroup("如龙", listOf("如龙8", "如龙7", "如龙0", "如龙", "Yakuza 8", "Yakuza 7", "Yakuza 0", "Yakuza", "人中之龙8", "人中之龙7", "人中之龙0", "人中之龙", "如龙8无尽财富", "Like a Dragon"), listOf(
        CharEntry("向田纱荣子", listOf("向田纱荣子", "纱荣子", "Saeko")),
        CharEntry("狭山薰", listOf("狭山薰", "Kaoru")),
        CharEntry("泽村遥", listOf("泽村遥", "Haruka"))
    )),
    SourceGroup("仙剑奇侠传", listOf("仙剑奇侠传", "仙剑"), listOf(
        CharEntry("赵灵儿", listOf("赵灵儿", "灵儿")),
        CharEntry("林月如", listOf("林月如", "月如")),
        CharEntry("阿奴", listOf("阿奴", "Anu")),
        CharEntry("唐雪见", listOf("唐雪见", "雪见")),
        CharEntry("龙葵", listOf("龙葵")),
        CharEntry("紫萱", listOf("紫萱")),
        CharEntry("柳梦璃", listOf("柳梦璃", "梦璃")),
        CharEntry("韩菱纱", listOf("韩菱纱", "菱纱")),
        CharEntry("越祈", listOf("越祈"))
    )),
    SourceGroup("古剑奇谭", listOf("古剑奇谭", "古剑"), listOf(
        CharEntry("风晴雪", listOf("风晴雪", "晴雪")),
        CharEntry("襄铃", listOf("襄铃")),
        CharEntry("闻人羽", listOf("闻人羽")),
        CharEntry("乐无异", listOf("乐无异")),
        CharEntry("北洛", listOf("北洛"))
    )),
    SourceGroup("逆水寒", listOf("逆水寒"), listOf(
        CharEntry("苏梦枕", listOf("苏梦枕")),
        CharEntry("温柔", listOf("温柔"))
    )),
    SourceGroup("剑网3", listOf("剑网3", "剑网 3", "剑侠情缘3"), listOf(
        CharEntry("洛风", listOf("洛风")),
        CharEntry("叶芷青", listOf("叶芷青")),
        CharEntry("李复", listOf("李复"))
    )),
    SourceGroup("黑神话 悟空", listOf("黑神话 悟空", "黑神话悟空", "Black Myth Wukong"), listOf(
        CharEntry("四妹", listOf("四妹")),
        CharEntry("萍萍", listOf("萍萍")),
        CharEntry("铁扇公主", listOf("铁扇公主")),
        CharEntry("蜘蛛精", listOf("蜘蛛精"))
    )),
    SourceGroup("饿狼传说", listOf("饿狼传说", "Fatal Fury", "Garou", "饿狼传说群狼之证", "Garou Mark of the Wolves"), listOf(
        CharEntry("不知火舞", listOf("不知火舞", "Mai Shiranui", "舞", "Mai")),
        CharEntry("布鲁玛丽", listOf("布鲁玛丽", "Blue Mary", "玛丽")),
        CharEntry("李香绯", listOf("李香绯", "Li Xiangfei")),
        CharEntry("邦妮", listOf("邦妮", "Bonne Jenet", "Jenet"))
    )),
    SourceGroup("葬送的芙莉莲", listOf("葬送的芙莉莲", "芙莉莲", "Frieren", "Sousou no Frieren"), listOf(
        CharEntry("芙莉莲", listOf("芙莉莲", "Frieren")),
        CharEntry("菲伦", listOf("菲伦", "Fern")),
        CharEntry("修塔尔克", listOf("修塔尔克", "Stark")),
        CharEntry("古拉欧萨", listOf("古拉欧萨", "Lügner")),
        CharEntry("莉涅尔", listOf("莉涅尔", "Liene")),
        CharEntry("拉奥芬", listOf("拉奥芬", "Lawine")),
        CharEntry("克蕾芙", listOf("克蕾芙", "Kraft"))
    )),
    SourceGroup("第一后裔", listOf("第一后裔", "The First Descendant", "第一后裔 邦尼"), listOf(
        CharEntry("邦妮", listOf("邦妮", "Bunny", "邦尼")),
        CharEntry("维艾莎", listOf("维艾莎", "Viessa")),
        CharEntry("雷普西", listOf("雷普西", "Lepic")),
        CharEntry("弗蕾娜", listOf("弗蕾娜", "Freyna")),
        CharEntry("布莱尔", listOf("布莱尔", "Blair")),
        CharEntry("沙迪克", listOf("沙迪克", "Sharen")),
        CharEntry("露娜", listOf("露娜", "Luna")),
        CharEntry("席莲", listOf("席莲", "Sienne")),
        CharEntry("瓦尔比", listOf("瓦尔比", "Valby")),
        CharEntry("耶娜", listOf("耶娜", "Yujin"))
    )),
    SourceGroup("最后的生还者", listOf("最后的生还者", "美国末日", "The Last of Us", "TLOU", "The Last of Us Part 1", "The Last of Us Part 2", "最后生还者"), listOf(
        CharEntry("艾莉", listOf("艾莉", "Ellie")),
        CharEntry("泰丝", listOf("泰丝", "Tess")),
        CharEntry("迪娜", listOf("迪娜", "Dina")),
        CharEntry("艾比", listOf("艾比", "Abby")),
        CharEntry("莱莉", listOf("莱莉", "Riley")),
        CharEntry("玛琳", listOf("玛琳", "Marlene"))
    )),
    SourceGroup("无限暖暖", listOf("无限暖暖", "Infinity Nikki", "暖暖", "奇迹暖暖", "闪耀暖暖"), listOf(
        CharEntry("暖暖", listOf("暖暖", "Nikki"))
    )),
    SourceGroup("漫威争锋", listOf("漫威争锋", "Marvel Rivals"), listOf(
        CharEntry("黑寡妇", listOf("黑寡妇", "Black Widow", "娜塔莎")),
        CharEntry("猩红女巫", listOf("猩红女巫", "绯红女巫", "Scarlet Witch", "旺达", "Wanda")),
        CharEntry("魔卡娜", listOf("魔卡娜", "Magik", "伊利亚娜")),
        CharEntry("灵蝶", listOf("灵蝶", "Psylocke", "蝶")),
        CharEntry("隐形女", listOf("隐形女", "Invisible Woman", "苏珊")),
        CharEntry("松鼠女", listOf("松鼠女", "Squirrel Girl")),
        CharEntry("暴风女", listOf("暴风女", "Storm")),
        CharEntry("琴格雷", listOf("琴格雷", "Jean Grey", "琴", "凤凰女")),
        CharEntry("海拉", listOf("海拉", "Hela")),
        CharEntry("魔形女", listOf("魔形女", "Mystique"))
    )),
    SourceGroup("名侦探柯南", listOf("名侦探柯南", "柯南", "Detective Conan", "Case Closed"), listOf(
        CharEntry("毛利兰", listOf("毛利兰", "小兰", "兰", "Ran", "Ran Mouri")),
        CharEntry("灰原哀", listOf("灰原哀", "小哀", "哀", "Haibara", "Ai Haibara", "宫野志保", "雪莉")),
        CharEntry("铃木园子", listOf("铃木园子", "园子", "Sonoko")),
        CharEntry("远山和叶", listOf("远山和叶", "和叶", "Kazuha")),
        CharEntry("工藤有希子", listOf("工藤有希子", "有希子", "Yukiko")),
        CharEntry("贝尔摩德", listOf("贝尔摩德", "苦艾酒", "Vermouth", "莎朗温亚德")),
        CharEntry("水无怜奈", listOf("水无怜奈", "基尔", "Kir", "Mizunashi Rena")),
        CharEntry("世良真纯", listOf("世良真纯", "真纯", "Sera", "Mary"))
    )),
    SourceGroup("银魂", listOf("银魂", "Gintama", "银之魂"), listOf(
        CharEntry("神乐", listOf("神乐", "Kagura", "夜兔神乐")),
        CharEntry("志村妙", listOf("志村妙", "阿妙", "Tae", "Otae")),
        CharEntry("猿飞菖蒲", listOf("猿飞菖蒲", "菖蒲", "Sacchan", "Saigou")),
        CharEntry("月咏", listOf("月咏", "Tsukuyo")),
        CharEntry("柳生九兵卫", listOf("柳生九兵卫", "九兵卫", "Kyubei"))
    )),
    SourceGroup("犬夜叉", listOf("犬夜叉", "Inuyasha"), listOf(
        CharEntry("日暮戈薇", listOf("日暮戈薇", "戈薇", "Kagome")),
        CharEntry("桔梗", listOf("桔梗", "Kikyo", "Kikyou")),
        CharEntry("珊瑚", listOf("珊瑚", "Sango"))
    )),
    SourceGroup("美少女战士", listOf("美少女战士", "Sailor Moon", "美战"), listOf(
        CharEntry("月野兔", listOf("月野兔", "水手月亮", "Sailor Moon", "Usagi", "小兔")),
        CharEntry("水野亚美", listOf("水野亚美", "水手水星", "Sailor Mercury", "Ami")),
        CharEntry("火野丽", listOf("火野丽", "水手火星", "Sailor Mars", "Rei")),
        CharEntry("木野真琴", listOf("木野真琴", "水手木星", "Sailor Jupiter", "Makoto")),
        CharEntry("爱野美奈子", listOf("爱野美奈子", "水手金星", "Sailor Venus", "Minako"))
    )),
    SourceGroup("钢之炼金术师", listOf("钢之炼金术师", "钢炼", "Fullmetal Alchemist", "FMA"), listOf(
        CharEntry("温莉", listOf("温莉", "Winry", "温莉洛克贝尔")),
        CharEntry("莉莎", listOf("莉莎", "Riza", "莉莎霍克艾", "霍克艾")),
        CharEntry("兰芳", listOf("兰芳", "Lan Fan")),
        CharEntry("罗莎", listOf("罗莎", "Rosé"))
    )),
    SourceGroup("东京喰种", listOf("东京喰种", "东京食尸鬼", "Tokyo Ghoul"), listOf(
        CharEntry("雾嶋董香", listOf("雾嶋董香", "董香", "Touka")),
        CharEntry("神代利世", listOf("神代利世", "利世", "Rize")),
        CharEntry("芳村艾特", listOf("芳村艾特", "艾特", "Eto", "独眼枭"))
    )),
    SourceGroup("排球少年", listOf("排球少年", "Haikyuu", "排球"), listOf(
        CharEntry("清水洁子", listOf("清水洁子", "洁子", "Kiyoko")),
        CharEntry("谷地仁花", listOf("谷地仁花", "仁花", "Yachi", "谷地"))
    )),
    SourceGroup("猫娘乐园", listOf("猫娘乐园", "Nekopara"), listOf(
        CharEntry("巧克力", listOf("巧克力", "Chocola")),
        CharEntry("香草", listOf("香草", "Vanilla")),
        CharEntry("肉桂", listOf("肉桂", "Cinnamon")),
        CharEntry("枫糖", listOf("枫糖", "Maple")),
        CharEntry("椰子", listOf("椰子", "Coconut"))
    )),
    SourceGroup("虚拟主播", listOf("虚拟主播", "VTuber", "ホロライブ", "Hololive"), listOf(
        CharEntry("宝钟玛琳", listOf("宝钟玛琳", "Marine", "船长")),
        CharEntry("Fuwawa", listOf("Fuwawa", "fuwawa")),
        CharEntry("Mococo", listOf("Mococo", "mococo"))
    )),
    SourceGroup("我独自升级", listOf("我独自升级", "Solo Leveling"), listOf(
        CharEntry("成珍雅", listOf("成珍雅", "Cha Hae-In"))
    )),
    SourceGroup("黑暗之魂3", listOf("黑暗之魂3", "Dark Souls 3", "黑魂3"), listOf(
        CharEntry("防火女", listOf("防火女", "Fire Keeper"))
    )),
    SourceGroup("明日方舟 终末地", listOf("明日方舟 终末地", "Arknights Endfield"), listOf(
        CharEntry("伊冯", listOf("伊冯"))
    )),
    SourceGroup("斗罗大陆", listOf("斗罗大陆"), listOf(
        CharEntry("王冬儿", listOf("王冬儿", "霍雨浩"))
    )),
    SourceGroup("原创角色", listOf("原创角色", "OC", "Original Character"), listOf(
        CharEntry("Primrose", listOf("Primrose", "普丽姆罗丝"))
    ))
)
